### ISSUE TITLE
Link to live examples from README.md

### ISSUE THREAD

**Issue by sole** [tweenjs/tween.js#109]
... not to the source code

**Comment by sole** [comment]
Perhaps we could use CodeMirror? Or perhaps we could have a repository of just examples, that provides two 'panes' - one with editable source and another one with the output?
 
Ideally we can avoid using hosted services such as JSFiddle or similar because they do not work well offline, and it's also hard to get a copy of all the demos with just one `git clone` away.

**Comment by mikebolt** [comment]
README.md now has a CodePen for the main code sample at the top. I created #450 for doing the same thing for the code samples in the user guide.
