### ISSUE TITLE
Multiple callbacks

### ISSUE THREAD

**Issue by Kalabasa** [tweenjs/tween.js#120]
Can we allow multiple callbacks instead of one per event?

Example usage:

```
// add two onComplete callbacks
tween.onComplete(func1);
tween.onComplete(func2);
```

I actually implemented this partially (only for onComplete callbacks) so will this be a useful addition?

This is the actual use case (why I implemented this feature):

```
function enqueue_tween(tween){
    if(tween_chain_last){
        tween_chain_last.chain(tween);
    }else{
        tween.start();
    }
    tween_chain_last = tween;
    tween_chain_last.onComplete(function(){
        if(tween_chain_last == tween){
            tween_chain_last = null;
        }
    });
}
```

I used this for sequencing on the fly.

**Comment by accidentallyc** [comment]
Hello, reopening. Sorry for this! I first experienced this programming idiom on Phaser.
I think a better example of a use case would be something like this ->
```
 function move (PlayerOrObject){
  return tween(...).onComplete( ... ) // tween something then cleanup
}

function movePlayer(){
  let passedTween = move( Some_Player )
  return passedTween.onComplete( ... ) // update something related to player
}

function mainTutorial(){
  movePlayer().onComplete(function(){
    alert( "Good job!")
  })
}
```
In this example, the tween is being passed around . It's not a terribly important feature but yeah.



In my custom version of three js i modified the onComplete fn to be something like this to chain it 
```
  if( _onCompleteCallback ){
      let temp = _onCompleteCallback
      _onCompleteCallback = function(){
        temp(),callback()
      };
    }else{
      _onCompleteCallback = callback;
    }
```
Atleast that way, there would'nt be too much refactoring required.

**Comment by mikebolt** [comment]
This would be a breaking change unless we made a new function such as
"addOnComplete", and "onComplete" reset the callback list.

**Comment by accidentallyc** [comment]
Yeah totally. Would have been a nice feature to have unless people are
actively avoiding it for some reason.
