### ISSUE TITLE
Make it more explicit that you can get tween.js via npm

### ISSUE THREAD

**Issue by sole** [tweenjs/tween.js#122]
Explain how to get the library in general (git clone, download the ZIP, npm)

Maybe add an npm badge or something like that too? So people are aware that npm builds exist already (re: #121)

**Comment by Wexcode** [comment]
https://www.npmjs.com/package/tween.js

**Comment by sole** [comment]
@Wexcode ?

**Comment by Wexcode** [comment]
Got a bit lost trying to find the name of the package on npm (not sure why I didn't immediately see it in the readme), and ended up on this page. I posted the link here to help shortcut the next person's discovery process.
