### ISSUE TITLE
Bower problems - url should point to https://github.com/tweenjs/tween.js.git , not the git@ private address

### ISSUE THREAD

**Issue by lcnvdl** [tweenjs/tween.js#138]
Hi Sole, please see my attachment.
Regards!

Hola Sole, por favor mirá mi imagen adjunta.
Saludos!

![problem](https://cloud.githubusercontent.com/assets/5065981/3991019/77148c46-28d9-11e4-8ead-43b6fc73134a.png)

**Comment by sole** [comment]
You're right, the url should be the public one, not my git@github address. Thanks for reporting!
