### ISSUE TITLE
onStart() not working according to the user guide

### ISSUE THREAD

**Issue by BryanMorgan** [tweenjs/tween.js#146]
The Callbacks section of the user guide says the onStart callback can be used to reset values:

"Executed right before the tween starts-i.e. before the deltas are calculated. This is the place to reset values in order to have the tween always start from the same point, for example."

However if you try to run the example in the documentation, the value of this.x is not picked up for calculations. Here's a JSFiddle with an example of setting x = 200 - notice it doesn't get picked up and the default  = 50 value is still used:

http://jsfiddle.net/BryanMorgan/trL3k6j1/

The reason is that _valuesStart is not reset after the onStart callback is called, so the original values in the constructor are always used in the calculations.

**Comment by jcarpenter** [comment]
Hmm, hit the same issue today...
