### ISSUE TITLE
Using relative values in 'array of values' tween

### ISSUE THREAD

**Issue by sinujohn** [tweenjs/tween.js#150]
Currently it is not possible to use relative values (string values like "+50") when tweening to arrays of values.
For example, if relative values were allowed, the following code makes a sprite jump 3 times:

``` javascript
var tween3 = new TWEEN.Tween(position)
                .to({x: ["+50", "+50"],
                    y: ["-50", "+50"]})
                .repeat(2)
                .onUpdate(function() {
                    bunny.position.x = position.x;
                    bunny.position.y = position.y;
                });
tween3.start();
```

Can this be added in a future release?

**Comment by yqrashawn** [comment]
Still not added?

**Comment by sole** [comment]
@yqrashawn no. Do you want to chime in and contribute some code? That would be lovely 😃

**Comment by yqrashawn** [comment]
Maybe next month, when fininsh my project. Maybe still busy next month.

**Comment by mikebolt** [comment]
@sole Do you think it would work to convert arrays with relative values to
non-relative arrays first? If so, this wouldn't be difficult. Probably 5
lines of code all in one place.

**Comment by sole** [comment]
@mikebolt but the relative values are computed each time the tween is re-started, how would you account for that? Sounds a bit more than 5 lines of code but maybe I'm overengineering!

**Comment by trusktr** [comment]
This was recently added and tested!

**Comment by trusktr** [comment]
> but the relative values are computed each time the tween is re-started, how would you account for that? Sounds a bit more than 5 lines of code but maybe I'm overengineering!


This is currently the case, but when I was looking at the code I saw a way we can just apply values each time the tween starts. Coming soon...
