### ISSUE TITLE
chain method syntax is pretty terrible/unclear

### ISSUE THREAD

**Issue by sole** [tweenjs/tween.js#153]
If you chain one thing it works fine
If you chain two things consecutively only the last one gets chained (?)
If you want to chain several with an array, you need to use `tween.apply(tween, saidArray)` (!?)

that is pretty awkward and error prone!

**Comment by sole** [comment]
Not really, I filed the bug to get the thoughts started :-)

**Comment by sole** [comment]
(also sorry about the delay in coming back to this-I haven't been getting notifications, ugh)

**Comment by thednp** [comment]
The `.chain()` method should create an array of chained tweens and the update function should take care of that.

**Comment by thednp** [comment]
The above solution works fine, but the original code is fine as well.

We can tween multiple tweens like so `tween.chain(tween1,tween2)`. 
So I tested it's fine. We only need to document the chain method.

**Comment by trusktr** [comment]
Nowadays we can easily pass an array with `.chain(...tweensToChain)`, so I'll just close this. Feel free to reply if you have any ideas on how to improve it beyond the builtin syntax.
