### ISSUE TITLE
[Question] How can I update the time value while a tween is running?

### ISSUE THREAD

**Issue by webtech1980** [tweenjs/tween.js#172]
Hello and sorry if this is not the correct way to ask a question. It's my first time using GitHub. I would like to know if there is any way to update the time value while a tween is running. For example I'm trying to do some thing like this.

var redTargetStart = new TWEEN.Tween(object.position).to(end.position, timeValue);
				     redTargetStart.onUpdate(function() {
					 if (Math.abs(object.position.x) < 275 && Math.abs(object.position.z) < 275)   {
						     timeValue /= 2;
					 }
					 if (Math.abs(object.position.x) < 175 && Math.abs(object.position.z) < 175) {
					         timeValue /= 2;
					 }
					 if (Math.abs(object.position.x) < 75 && Math.abs(object.position.z) < 75) {
					         timeValue /= 2;
					 }
				 });

This way I would be doubling the speed of my object every so often. It seems like just updating the value is not enough. Is there any way to make the tween see the change?

**Comment by sole** [comment]
The idea of tweens is that they're more declarative than imperative, and so what you're doing here would change the overall time - if there are more linked tweens it would get out of whack/sync.

So no, it's not possible to do that unless you do weird hacks, I guess :-)
