### ISSUE TITLE
repeat with yoyo doesn't work properly

### ISSUE THREAD

**Issue by dnassler** [tweenjs/tween.js#173]
When I try to setup a tween that repeats with yoyo, my tween repeats but doesn't do the yoyo part. :(

**Comment by sole** [comment]
We should investigate this behaviour and also add @thednp's comment to the documentation if it's the right behaviour. Or perhaps see if the docs are confusing.

**Comment by trusktr** [comment]
We're gonna get things rolling again. Tracking in the new project board: https://github.com/tweenjs/tween.js/projects

**Comment by trusktr** [comment]
Closing this, as there isn't a description of what's wrong. There have been fixes to yoyo functionality recently, and it is tested and working in the examples (make sure to call `repeat` with a value of `1` or more).
