### ISSUE TITLE
Tweens don't respect the 'repeat' method when chained cyclically.

### ISSUE THREAD

**Issue by sinujohn** [tweenjs/tween.js#176]
Hi all,
I had mentioned this over here: https://github.com/sole/tween.js/issues/71
But since that was a closed issue, I don't think anyone noticed it. So here it is.

I find 'repeat' working a bit strangely. Don't know whether this is how it was intended to be. 
Repeat is only considered the first time a tween runs.
Example code:

``` javascript
        var position = {x: 0};
        var tween0 = new TWEEN.Tween(position)
                .to({x: "+50"}, 1000)
                .repeat(1)
                .onComplete(function() {
                    console.log("Tween 0 completed. X is " + this.x);
                });
        var tween1 = new TWEEN.Tween(position)
                .to({x: "-50"}, 1000)
                .repeat(1)
                .onComplete(function() {
                    console.log("Tween 1 completed. X is " + this.x);
                });
         tween0.chain(tween1);
         tween1.chain(tween0);
         tween0.start();
```

Output I am expecting is 

```
Tween 0 completed. X is 100
Tween 1 completed. X is 0
Tween 0 completed. X is 100
Tween 1 completed. X is 0
Tween 0 completed. X is 100
Tween 1 completed. X is 0
 ...
Tween 0 completed. X is 100
Tween 1 completed. X is 0
```

But the obtained output is 

```
Tween 0 completed. X is 100
Tween 1 completed. X is 0
Tween 0 completed. X is 50
Tween 1 completed. X is 0
Tween 0 completed. X is 50
Tween 1 completed. X is 0
 ...
Tween 0 completed. X is 50
Tween 1 completed. X is 0
```

**Comment by sole** [comment]
Interesting catch! Perhaps we're missing on some resetting of the repeat value.

**Comment by trusktr** [comment]
I fixed this (and some other issues) recently (along with new tests) by improving how a tween's state is reset when calling `tween.start()` to restart it. Please feel free to reply or make a new issue if any issues still persist.
