### ISSUE TITLE
Yoyo not working properly when relative values are used

### ISSUE THREAD

**Issue by sinujohn** [tweenjs/tween.js#178]
If we use relative values in a tween and yoyo() along with it, then its not working as expected. Following code shows the error:

```
var position = {x:0, y:150};
        var tween0 = new TWEEN.Tween(position)
                .to({x: "+50"}, 1000)
                .repeat(1)
                .yoyo(true)
                .onComplete(function() {
                    console.log("Tween 0 completed. X is " + this.x);
                })
                .onUpdate(function() {
                    console.log("x:" + this.x);
                });
        tween0.start();
```

Here the value of 'x' should be between 0 and 50 (both included), but its going out of this range, like values 500.

**Comment by sole** [comment]
@sinujohn thanks for the PR, let me review it as soon as possible. I missed notifications on this repo for the last months :-(

**Comment by trusktr** [comment]
fixing in https://github.com/tweenjs/tween.js/pull/179

**Comment by trusktr** [comment]
Tracking in the new project board: https://github.com/tweenjs/tween.js/projects
