### ISSUE TITLE
Getting tween state in the middle

### ISSUE THREAD

**Issue by khurramraheel** [tweenjs/tween.js#181]
I know its a silly question but is it possible to move the tween object my assigning some time value, like if I have a tween which has a duration of 10 seconds, Is there any way to start the tween and directly move to my desired time , for example what If I want to move my tween to move to 6 seconds or say 5 seconds and start from there?

**Comment by sole** [comment]
Not right now with the current API, unless you did some sort of 'hack' like starting the tween at a t=0 and then immediately updating to t=5 and continuing from there. I haven't done it myself.
Sorry about the delay, I missed the notifications.

**Comment by humodz** [comment]
You can pass an argument to `tween.start()`:
```js
// Sets the start time to 6 secs in the past
myTween.stop().start(TWEEN.now() - 6000)
// or
myTween.stop().start(String(-6000));
```

Full example:
https://jsbin.com/mayafehoye/11/edit?html,js,output
