### ISSUE TITLE
Typo on NPM

### ISSUE THREAD

**Issue by ponychicken** [tweenjs/tween.js#184]
On https://www.npmjs.com/package/tween.js:

    Then use browserify or your npm tool of choice, or just include the module using the standard node require:

    var TWEEN = require('.tween.js');
                         ^
                         ^

**Comment by sole** [comment]
Please send a PR?

**Comment by ponychicken** [comment]
It's correct in Readme.md, I think you might need to republish? I don't know where the npm text comes from precisely

**Comment by sole** [comment]
uuuh maybe! Sorry about this, I found yesterday that I hadn't got notifications for these issues for 2 months and I'm a bit aaaah!

thanks for bringing it up <3

**Comment by sole** [comment]
Now fixed - sorry, life gets in my way all so often!

thanks for bringing it up, again!
