### ISSUE TITLE
[trivial] _valuesEnd [property] must also be checked to be a number

### ISSUE THREAD

**Issue by thednp** [tweenjs/tween.js#191]
When dealing with opacity tweening it seems to work ok, but when dealing with transform scale, I always get the object scaling up (from 1.5 to 2.5) instead of scaling down (from 1 to 0.5).

The below fixes the problem inside this.start function

<pre>
	if( ( _valuesEnd[ property ] instanceof Array ) === false ) {
		_valuesEnd[ property ] *= 1.0; // Ensures we're using numbers, not strings
	}
</pre>

**Comment by dalisoft** [comment]
This issue fixed in my modified mini animation library - animo.js ( https://github.com/dalisoft/animo.js ). Also have animo.js data plug-in for using animation with HTML5 Attributes ( https://github.com/dalisoft/animo.data.js )

**Comment by sole** [comment]
this is in the repo now, not sure when it was added but... should be cool. Thanks @thednp !
