### ISSUE TITLE
how to skip some "tick" when in onUpdate event?

### ISSUE THREAD

**Issue by futurist** [tweenjs/tween.js#193]
##How to skip some tick on the passed in _onUpdateCallback?

for example, 
```javascript
	var startTime=new Date();
	tween.onUpdate(function(){
	
		var t=new Date() - startTime;
	    if( t>1000 && t<2000 ) return;
	    
	    update_some_thing();
	});
```

Here I need the animation stop between 1 and 2 sec, but after that I need the animation continue from last position.

How to do that?

I've tried but the animation jumped, not continuing.

**Comment by sole** [comment]
there's no method in the API that does it. Perhaps you can divide your movements in two, create two tweens and chain one after the other, and make it start after a certain time with the delay method.
