### ISSUE TITLE
Can I tie a tween.js tween to mouse scroll movement?

### ISSUE THREAD

**Issue by laughingturtle** [tweenjs/tween.js#194]
Can tween.js tie a tween to the y position of the mouse? So you can basically  'scroll' the tween?
So you move your mouse up, the tween happens, move it down it reverses, but move it up just a little and the tween happens just a little. I'm wondering if tween.js can do something like this, and if so how?

So the tween would update with the mouse movement, but I'd always want the tween to happen between y 250 and y 300 - just that the tween would start at 250, and move 20% by y 260, reverse 10% if I scroll back to y 255 etc - so the tween would be dictated by the mouse movement.

**Comment by sole** [comment]
Not by itself. You could stop the tween and set the `to` values when the mouse is moved, and then start the tween again. There is also an example of dynamic to values, perhaps it might help you
https://github.com/tweenjs/tween.js/blob/master/examples/07_dynamic_to.html
