### ISSUE TITLE
mobile version?

### ISSUE THREAD

**Issue by rlech** [tweenjs/tween.js#196]
is there any chance for mobile support in the future?

**Comment by sole** [comment]
I don't understand what you want from a "mobile" version. Sincere question: what is stopping you from using this on a mobile device?

**Comment by rlech** [comment]
I´m using tween.js for a cordova/phonegap build with meteor. Its working in my browser but its not working on my mobile devices. Also the examples don´t work.

**Comment by dalisoft** [comment]
Hi @rlech!
I am tested this Javascript Tweening Engine on all devices and works fine, i created some animation engine with this. I think have issue with your code, please re-check or let me link, i check and say what issue with code. 
* requestAnimationFrame is doesn't support natively in some browsers!

**Comment by rlech** [comment]
mhmm strange i´ve tested the example page with my iphone 6p
https://github.com/tweenjs/tween.js

not all of them work like in my safari browser on my macbook.

for my project I just want to incease a number from 0 to x via a curve (

my code


Template.profile.rendered = function () {

    // wait for animation
    setTimeout(function () {
        init();

        animate();
    }, 1500);


    function init() {

        var output = document.getElementById('inceaseMe');

        var tween = new TWEEN.Tween({x: 0})
            .to({x: 400}, 2000)
            .easing(TWEEN.Easing.Exponential.Out)
            .onUpdate(function () {

                output.innerHTML = Math.round(this.x);

            })
            .start();

    }

    function animate(time) {

        requestAnimationFrame(animate); // js/RequestAnimationFrame.js needs to be included too.
        TWEEN.update(time);

    }
};


I´ve just c&p the example code

**Comment by dalisoft** [comment]
```javascript
// wait for animation
setTimeout(function () {
    init();
}, 1500);


function init() {

    var output = document.getElementById('inceaseMe');

    var tween = new TWEEN.Tween({x: 0})
        .to({x: 400}, 2000)
        .easing(TWEEN.Easing.Exponential.Out)
        .onUpdate(function () {

            output.innerHTML = Math.round(this.x);

        })
        .start();

}

function animate(time) {

    requestAnimationFrame(animate); // js/RequestAnimationFrame.js needs to be included too.
    TWEEN.update(time);

}
animate(0);
```

I'm also using phonegap/cordova with small knowledge, but i'm not using render like your Template.profile.rendered. I think this is issue, you also called Template.profile.rendered()???

Check this update

**Comment by rlech** [comment]
I´m using meteor (www.meteor.com)
Template.profile.rendered is just saying to run the code after the template (profile) was rendered. its the common way in meteor to do so. 

My code is working on a Android build (HTC One 7) and in my Browser (Safari Macbook Air) but its not working with an iOS Build (iPhone 6 Plus). its stopping after some frames and freezes the counter on my iPhone

**Comment by dalisoft** [comment]
Frame drops/stops after few frames or not tweening?

**Comment by rlech** [comment]
it always stops after 3-4 frames on ios

**Comment by dalisoft** [comment]
check last code, paste inside rendered

**Comment by rlech** [comment]
I get now 999+ errors in the browser console

errormessage "TypeError: null is not an object (evaluating 'output.innerHTML = Math.round(this.x)')"

**Comment by dalisoft** [comment]
Sorry, i don't understand your code

**Comment by PetersonLian** [comment]
@rlech I may have known what is your problem.  
It is your ` var tween = new TWEENblablabla.start()` went wrong.  
How do i put this?Let's say:  
when you evoke 'tween.start()', 'tweenjs' will set `_startTime` to the exact point when you evoke `start()` function.  
when you evoke 'TWEEN.update(time)', 'tweenjs' will set `time` to the passed parameter if given or the exact point when you evoke 'TWEEN.update` function.  Check out the following code from 'tweenjs'   
   
    time = time !== undefined ? time : ( typeof window !== 'undefined' && window.performance !== undefined && window.performance.now !== undefined ? window.performance.now() : Date.now() );
    ...
    var elapsed = ( time - _startTime ) / _duration;
    
The 'elapsed' is used to determine whether you are still in animation process or the animation is over.  
If 'tweenjs' thinks the animation is over, 'tweenjs' will remove the 'tween'.  

So, check this scenario.  
I need to do the animation in 2500(2.5s) time.
At time 0, I evoke 'tween.start()'.  
Then I setTimeout(function{
    evoke 'TWEEN.update'
}, 3500(larger than 2500))  
In this given scenario,  frame will not even started.  

This is the reason why your frame stopped at random times.  Cause after random times, your `(time - _startTime)` is greater than `_duration` and 'tweenjs' stops it.  

Hope I could help. Apologize for my poor English. 
Anybody, correct me if I was wrong.
Good luck with your bug.

**Comment by ianbelcher** [comment]
I had the same issue today with TWEEN running within a cordova app running on iOS. Works everywhere else but breaks on iOS.

The issue for me was that the build version of tween.js appears to be quite old in this repo. The performance object is not available in iOS webkit by the looks of things and the polyfill at the start of the src file seems not to have yet made it in the the build version as yet.

Using the src version should hopefully solve your issue. Don't have the time for PR to update this sorry.

**Comment by sole** [comment]
thanks for the research!

I should have more time in the upcoming weeks to work on tween, I'll try to prioritise this.

**Comment by thomasklein** [comment]
I confirm, the "performance.now polyfill" at the beginning of r15 made it work for me in iOS.

**Comment by wangzuo** [comment]
One way to fix the `window.performance.now` issue may be to use a build system on npm like [browserify](https://github.com/substack/node-browserify). [npm/performance-now](https://www.npmjs.com/package/performance-now) and [npm/xhr](https://www.npmjs.com/package/xhr) are both quite well maintained projects so actually no need to do it again in tween.js.

**Comment by sole** [comment]
this should all work now that we're not using a minified version that gets out of sync often. please report if you get issues in mobile platforms, thanks!
