### ISSUE TITLE
BOWER - need examples and someone who uses it to verify it's the best use case

### ISSUE THREAD

**Issue by sole** [tweenjs/tween.js#205]
I don't use bower but people seem to want to use it so they've contributed bower-related stuff.
We don't have any example of how to use bower other than some (I think wrong) mentions in the README.md

If the people who've contributed to the bower stuff wouldn't mind helping here, it will help a ton of other bower users as well :-)

Calling @azachar @novemberalpha for help! and thanks in advance =)

**Comment by claudiopro** [comment]
There are a few issues:
* tweenjs points to `https://github.com/sole/tween.js` (which itself redirects to `https://github.com/tweenjs/tween.js`):
```
$ bower install tweenjs --save
bower tweenjs#*             not-cached git://github.com/sole/tween.js.git#*
bower tweenjs#*                resolve git://github.com/sole/tween.js.git#*
bower tweenjs#*               checkout master
bower tweenjs#*               progress Receiving objects:  96% (75/78), 5.02 MiB | 686.00 KiB/s
bower tweenjs#*               progress Receiving objects:  96% (75/78), 5.18 MiB | 538.00 KiB/s
bower tweenjs#*               progress Resolving deltas: 100% (7/7), done.
bower tweenjs#*               resolved git://github.com/sole/tween.js.git#42141d36dd
bower tweenjs#*                install tweenjs#42141d36dd

tweenjs#42141d36dd bower_components/tweenjs
```
* You may want to add a `--save` flag to the `bower` command to save the dependency to `bower.json` 
* The directory is `bower_components/tweenjs`, not `bower_components/tween.js`.
* There's a garbled code block in the README:

```bash
bower install tweenjs#r14```
```

I suggest [requesting an update](https://github.com/bower/registry#unregister-package) to the bower registry

**Comment by sole** [comment]
Thank you @claudiopro this is great info! :+1:

**Comment by jfbibeau** [comment]
Any idea when can we expect a release of tween.js that will be tagged with the bower.json file? It'd be great to be able to do a `bower install tweenjs` and supply a stable version. Looks like r14 didn't include the bower.json yet. Anything I can help with?

**Comment by claudiopro** [comment]
@sole welcome :wink:

**Comment by sole** [comment]
@jfbibeau when I have time to do it, or someone steps up to help with that. I don't use bower so I totally forget about this. I am thinking about using semantic-release and should avoid these issues, but I have been travelling and conferencing lately and I have literally no spare time.
