### ISSUE TITLE
Removing the 'build' version as it's just such a little improvement vs 'uncompressed'

### ISSUE THREAD

**Issue by sole** [tweenjs/tween.js#206]
This made sense in 2009 or 2010 when the project was started (can't even remember) and people just included `<script>` tags in their code, but nowadays almost everyone uses some sort of build process and frankly if you don't, you probably don't care too much about using a minified or not version.

The last compressed build was about 5k vs about 13k for the original. It's ridiculous to have to spend time on this, and it gets out of sync all so often! (e.g. where this is an issue: #196)

We are now using npm and package.json which allows you to easily install and use this library. The build system essentially just uglifies the code and adds some headers to it so you know where it came from and which revision is it.

I think it would be worth to remove this kind of `dist`ributable version. Any thoughts?

**Comment by tofumatt** [comment]
> nowadays almost everyone uses some sort of build process

I _do_ wonder about this, but if it saves development effort and it's such a small size difference, I'd agree and say "don't offer a compressed version".

I'd love to do that with localForage, but the size diff for it is quite large. I say ditch it!
