### ISSUE TITLE
Performance polyfill does not work when tween.js is used as a module

### ISSUE THREAD

**Issue by stuartkeith** [tweenjs/tween.js#209]
The performance polyfill is enclosed in a self-executing anonymous function, where ``this`` is passed in as the object to which the polyfill will be attached.

When using tween.js as a module (```TWEEN = require('tween.js');```), ``this`` does not equal ``window`` - so the polyfill won't work.

I assume the current method is used for compatibility with environments that don't have the ``window`` variable - could something like ``typeof window !== 'undefined' ? window : this`` be used instead?

**Comment by dalisoft** [comment]
Hi @stuartkeith 
In last release tween.js includes shim/polyfill for performance.now with "this" access as global!
I confirm it's working on NodeWebkit project defined as module. Or you can use Date.now() (works everywhere)!
