### ISSUE TITLE
Mutliple tweens on a single property of the same object

### ISSUE THREAD

**Issue by brenwell** [tweenjs/tween.js#210]
First of all,  thanks for the library.

I have a question regarding the behaviour of tween js. Lets say I have an object with a `mouseover` and a `mouseoff` event. When the users triggers a `mouseover` event a tween occurs of 500ms on the object's `scale` attribute doubling it in size (x2). The user immediately moves the cursor after only 100ms firing the 'mouseoff' event which is of duration 100ms and scale's the image back down to 1. In this scenario tweenjs is trying to tween the `scale` property both up and down at the same time. From my tests I can see the the original `mouseover` event continues after the `mouseoff` has completed and results in the object being scaled and with the mouse off. 

Is there a hierarchy? which tween will be preformed when two or more are set on the same property, is it first-come-first-served or will new tween override existing ones.

And of lesser importance (because this must be possible) Is there away to tell tweenjs to cancel the first tween, if it has one ongoing, in favour of the new one?

Any insights into this behaviour would be great thanks.

**Comment by sole** [comment]
Hi!

Yes, you are correct. Tween is not tracking if there is another tween being run on the same property of the same object. It is first come first served. You will need to add some logic to make sure you don't try to run two tweens on the same object at the same time.

Tweens can be stopped and a new one made on the spot: https://github.com/tweenjs/tween.js/blob/master/docs/user_guide.md#controlling-a-tween

Hope this helps.

**Comment by brenwell** [comment]
Yep, thats a terrific answer. Thanks alot.
