### ISSUE TITLE
Supplied minified version doesn't have ios fix

### ISSUE THREAD

**Issue by skia** [tweenjs/tween.js#211]
Hi there, 
I downloaded the minified version from the build folder 
( https://raw.githubusercontent.com/tweenjs/tween.js/master/build/tween.min.js ) and it's not working on iOS 8.4 .
The not-minified version is working.

I didn't make many tests, so could be my code specific (even if it doesn't seems to).

**Comment by sole** [comment]
Please grab the unminified version.

https://github.com/tweenjs/tween.js/issues/206 should fix it, when it's done.

Sorry about that!
