### ISSUE TITLE
Use best practices in examples

### ISSUE THREAD

**Issue by sole** [tweenjs/tween.js#219]
Not using `top` and `left` but `transform` properties, etc

**Comment by sole** [comment]
Also simple html header without the long content-type `<meta>`. Goes from

`<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">`
to
`<meta charset="utf-8">`

**Comment by sole** [comment]
Also update the examples in the README so they don't use `top` or `left`

**Comment by dalisoft** [comment]
Hi @sole!
This is good idea, but tween.js main feature is working with older browser!
Why we need remove these properties or have polyfill for transform for IE 6-9, Opera less than 9 and etc?

**Comment by thednp** [comment]
Or make a <a href="http://thednp.github.io/kute.js/examples.html#crossbrowser">cross-browser</a> example.

**Comment by dalisoft** [comment]
* Use `will-change` on all properties, when using properties except for `transform`
* Use `transition: 1ms all; transform: translate3d(0px,0px,0px) rotateZ(360deg)` or `will-change: properties`
* Use `position: absolute` to slightly improve performance
* Use `display: none` when element is invisible (like `opacity:0`, `visibility:hidden`)
* Use `new TWEEN.Tween`, not a `TWEEN.Tween` for avoid bugs
* Always use latest build to get latest bug-fixes and improvements
* Use `CDN links` to reduce bandwidth, HTTP-request and latest update
