### ISSUE TITLE
[DID YOU KNOW?] Some tricks, maybe help you make animation better?!

### ISSUE THREAD

**Issue by dalisoft** [tweenjs/tween.js#227]
Hi, all!
I want share some tricks (if you want) to make web better!
Learn and test:
* if you remove ```<!DOCTYPE html>``` from html, for DOM Element animation ```px``` units are no need and animates with only numbers for like ```top, left, margin-left```! In case, it's improves performance!
* if you want smooth element animate for IE 6-9, use ```position:relative``` (animation will be smooth, like Chrome)
* if you want smooth and high performance element animation for Modern Browsers, use ```position:absolute``` (animation fps higher and no frame skipping)
* if you want smooth element ```transform``` (even borders), add ```outline: solid 1px transparent```
* Anyone have other tricks, comment

Thanks.
Sorry for my bad english.

**Comment by thednp** [comment]
That is really cool, but `<!DOCTYPE html>` is there to stay :)
