### ISSUE TITLE
Having IE9 Problems / Yes, he's still kicking.

### ISSUE THREAD

**Issue by leolo69** [tweenjs/tween.js#230]
First of all. Great Tweening-Engine! I'm normally using GASP but as filesize is unfortunately a great issue in banner production i did some searching and stumbled upon Tween.js. I was so happy and still am. Sadly i came across a problem i can't seem to solve on my own. crossbrowsertesting did show a problem  in ie9 (hate this guy but clients still want him included). i integrated your last uncompressed Tween.js version but nothing happens.

here's my codepen. maybe i'm just missing the obvious. Thanks ind advance.
alex

http://codepen.io/leolo/pen/RWLyow

**Comment by leolo69** [comment]
I found the solution. Inseringt "style.msTransform = transform;" does the magic.

**Comment by thednp** [comment]
You can check my <a href="http://thednp.github.io/kute.js">kute.js</a> if you're interested in size and simplicity, it's a fork of tween.js and with this
`var tween = KUTE.fromTo('selector', fromValues, toValues, options);`

you don't mind about browsers and such, doing the `onUpdate()` or `animate()` function everytime.

**Comment by leolo69** [comment]
thanks, this sounds interesting .. i'll have a look!

**Comment by sole** [comment]
Nice @thednp! 

Closing as resolved
