### ISSUE TITLE
Input frame count instead of time

### ISSUE THREAD

**Issue by trsh** [tweenjs/tween.js#238]
Right now tween.js takes duration as second parameter ".to({ x: 100, y: 100 }, 1000)", however sometimes you want more control over the frames, so it would be nice to have a function where we can pass steps count  ( ex. frame count) and receive the easing array. Ex

stepsXY = .steps({ x: 100, y: 100 }, 42) =  [{x:2.4, y:2.4}, {x:3.0, y:3.0}....]

then in my loop, I can use it like:

loop{
   posXY = stepsXY[frame]
}

**Comment by mikebolt** [comment]
Please help us figure out why a new function is necessary.

Your first option is to call TWEEN.update() inside the loop and pass it the frame number each time. Then everything should work as expected.

The second option is to provide an onUpdate callback for the tween that saves the values at each frame into an array, like so:
    
    var stepsXY = [];
    var tween = new TWEEN.Tween({x: 0, y: 0})
      .to({x: 100, y: 200}, 4)
      .onUpdate(function() {
        stepsXY.push({x: this.x, y: this.y});
      })
      .start();
    for (var i = 0; i <= 4; ++i) {
      tween.update(i);
    }

This should result in `stepsXY` holding the array `[{x: 0, y: 0}, {x: 25, y: 50}, {x: 50, y: 100}, {x: 75, y: 150}, {x: 100, y: 200}]`. Then you can use it however you like.

**Comment by trsh** [comment]
Ok. Thanks, will try like this

**Comment by sole** [comment]
Closing as resolved!
