### ISSUE TITLE
fps rate limit

### ISSUE THREAD

**Issue by strarsis** [tweenjs/tween.js#240]
Does tween.js limits the fps rate? Can I specify a fixed fps rate like 60fps?
Or should this be the scope of a different library, just for fps rate limiting?

Thank you and
with best regards

**Comment by mikebolt** [comment]
The recommended approach is to use requestAnimationFrame as follows:

    requestAnimationFrame(function(timestamp) {
        TWEEN.update(timestamp);
    });

The requestAnimationFrame function was designed and added to browsers for exactly this purpose. It does not always call the callback every 1/60 of a second, but it tries its best. It also does not let you specify a frame rate^[source](https://stackoverflow.com/questions/19000109/javascript-cant-adjust-framerate-requestanimationframe) .

Anyway, the answer is yes, this is not the responsibility of tween.js.

**Comment by sole** [comment]
And once again @mikebolt is correct!

Tween will be updated as fast as you make it update. The recommended approach is to use `requestAnimationFrame`: https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame

Closing bug, please reopen if you still have doubts
