### ISSUE TITLE
Function passed to Tween.call gets called before end of tween

### ISSUE THREAD

**Issue by JKE68** [tweenjs/tween.js#248]
If I run this code (taken from tween.js GettingStarted and slightly simplified) using tween.js 0.6.2

`
 
createjs.Tween.get(circle)                
    
    .to({x: 400}, 1000, createjs.Ease.getPowInOut(4))
    
    .call(function() {console.log("tween finished");})
    
    .addEventListener("change", function() {console.log("tween changed");} )
`

I get n times "tween changed", then "tween finished" and after that one more time "tween changed" in my console, leading me to the conclusion that the function passed to call is called too early, at least not after the tween has finished.

On a sidenote: if I first call addEventListener(..) on the Tween object and after that call(...) then the function passed to call isn't called at all.

**Comment by dalisoft** [comment]
Hi @JKE68!
I think you writed issue in wrong repository, because this tween.js not a by ```CreateJS```!!!

**Comment by sole** [comment]
Yep, this should go to the https://github.com/CreateJS/TweenJS repo. Thanks @dalisoft !
