### ISSUE TITLE
Issue playing back many tweens

### ISSUE THREAD

**Issue by fraguada** [tweenjs/tween.js#250]
Hello!  I've successfully implemented some basic camera tweening in a small app I have which uses Three.js and tween.js.  Going from one camera to another works well.  What I'd like to do is to animate from one camera to the next, that is, animate through all of the camera positions of the cameras I have in a scene.  I've made a [jsfiddle](https://jsfiddle.net/fraguada/4j0cfmLf/1/) which is a simplified version of what I'm seeing, which is essentially, only the last tween shows (I'm just writing out to the console, no graphics here).

Is there a way to build up tweens and play them all?  I've tried to create a starting tween, then using `.chain()` to add subsequent camera positions, but I got the same results.  Most of the examples seem to chain between two distinct tweens (i.e. back and forth).  Can multiple tweens be chained as such:

```
var baseTween = new TWEEN.Tween(...);
baseTween.chain(new TWEEN.Tween(...));
baseTween.chain(new TWEEN.Tween(...));
baseTween.chain(new TWEEN.Tween(...));
...
baseTween.start();
```
?

I believe I'm missing something fundamental in how this works.

p.s. I'm using the latest tween from master branch as of March 15th, 2016 and testing on osx 10.11.3/win 10, Chrome and Firefox

**Comment by mikebolt** [comment]
This line is a problem:

    TWEEN.removeAll();

At the end of the call to `init` you only had one registered tween, because the first three were removed by `TWEEN.removeAll()` at the beginning of the final iteration of the for loop.

If you remove only that line, then all the tweens will be registered, but they will all happen at the same time, and probably the most recently added one will override the others.

I got it working using the `chain` function. [Here's the jsfiddle](https://jsfiddle.net/4j0cfmLf/4/). Let me know if you have any questions.

**Comment by fraguada** [comment]
Hello @mikebolt.  Thank you very much for your help.  What I was thinking with `TWEEN.removeAll()` was that I create one tween, run it, remove all, and then run the next.  (I was obviously getting desperate).  I had also incorrectly interpreted chain and thought one should be able to chain many tweens with the pattern I wrote in the original comment.  The concept of 'chaining' one tween to another makes great sense.  Perhaps I'll have a go at a manner in which many tweens can be stacked to a nase tween.  Thanks again!

**Comment by sole** [comment]
@mikebolt thanks for the help!

@fraguada sorry about the issues you got with chain. The syntax needs a bit of thought, right now it's not intuitive but I haven't had time to think of a better solution yet.
