### ISSUE TITLE
Memory clean ?

### ISSUE THREAD

**Issue by damienfa** [tweenjs/tween.js#255]
I asked to myself if the Tween instance is properly deleted (and taken by the garbage collector) when it ends ?
Exemple : 
```
onClick() {
  var animationTween = new TWEEN.Tween(myElement);
  animationTween.to({ scrollTop: 0 }, 500).start();
}
```
In memory, it seems that, everytime `onClick` func is called, a new animationTween is created in memory and will be never cleared by the GC... Is it possible ? Memory Leak ?

**Comment by damienfa** [comment]
It seems that your `TWEEN.remove(this);` (line 184) should do the job... there is no more reference to the tween, so it will be deleted. 
I suppose that it's just my GC that have troubles. Just to know, is it ok in your memory profiler ? Or do you notice the same things that I ?

**Comment by mikebolt** [comment]
Yeah, the `_tweens` array is the only thing that holds on to the tween after creation, unless you also hold on to the reference.

Could you provide a memory graph of some kind, and a link to a codepen or a jsfiddle that causes the problem?

**Comment by dalisoft** [comment]
Hi all!
I sure, Tween.js is very best tweening engine.
I show part of code as remove tween when doesn't necessary
```javascript
while (i < _tweens.length) {

				if (_tweens[i].update(time)) { // if delay on tween, goes to next tween
					i++;
				} else {
					_tweens.splice(i, 1); // removes from array, improves performance and reduced while loop look-up
				}

			}
```
Thanks

**Comment by damienfa** [comment]
I had a very strange behaviour with my first tests, but the problem probably comes from my browser.
I've checked the code, and have made various complete tests : it looks all clean ! No memory leak.
Thanks a lot ! it's a great library !

**Comment by dalisoft** [comment]
I'm use this library more than 3-years and glad i helped others to understand thats fastest and clean tweening engine ever have, even used to THREE.js by @mrdoob 
Thanks.
If you want use more complex & advanced version of this engine, you can check my repo:
* `Unim.js` is very powerful animation engine that does almost all thing have in the web-animation
* `Animo.js` as light & minimal version of `Unim.js` does only necessary things and limited syntax's support
