### ISSUE TITLE
An updateTo() method (feature request?)

### ISSUE THREAD

**Issue by adrienbrunet** [tweenjs/tween.js#257]
Hi, I'd like to use tween.js for animation (and this library is awesome).
I need it to go from objectA to objectB. ObjectB is also constantly moving (including DURING the animation). I need to update the .to() position. Can we do that with the actual structure? I haven't found any issue or docs related to this problem.
Do we need a fonction let's say called "updateTo()" to do that? Cheers

**Comment by mikebolt** [comment]
Yeah, the library isn't designed to do this currently, but I think it's a good idea. I think instead of an `updateTo()` method, it would make more sense to have a method like `setDynamic()` which would set dynamic to true (or false with an argument) for that tween instance, then the current `update()` method would support both the regular and the dynamic kind of tweening, depending on the value of that property.

In the meantime, you can hack it by doing your own interpolation inside the `onUpdate()` method. Note that in this example I account for the possibility that both the start and the end positions are moving.

    var movingStart = {x: 5, y: 52};
    var movingTarget = {x: 12, y: 112};

    var object = {x: 5, y: 52};
    var tweenValue = {value: 0};

    TWEEN.Tween(tweenValue).setEasing(TWEEN.Easing.Cubic.InOut).to({value: 1})
      .onUpdate(function() {
        // Do some linear interpolation between the start and end values:
        object.x = movingStart.x + tweenValue.value * (movingTarget.x - movingStart.x);
        object.y = movingStart.y + tweenValue.value * (movingTarget.y - movingStart.y);
      }).start();

**Comment by JosephClay** [comment]
`updateTo` is very clear as to its intent. I'd prefer that to another [boolean trap.](http://ariya.ofilabs.com/2011/08/hall-of-api-shame-boolean-trap.html)

**Comment by mikebolt** [comment]
First of all, thanks for that article. That was a good read.

I don't think that, according to Hidayat, the `setDynamic` method I propose is a boolean trap, and I still think that's better than a separate update method. Here's my reasoning:

Its functionality not ambiguous or unintuitive. It sets the "dynamic" property of the tween, putting it in "dynamic mode".

According to [his other article](http://ariya.ofilabs.com/2012/06/detecting-boolean-traps-with-esprima.html), setters that start with "set" and that are not double negatives are fine.

The method will have no side effects besides setting the "dynamic" property. It will be a pure setter method, with only one argument.

"dynamic" should be considered a property of the tween.

I'm not sure how the tween would behave if you called `update()` then `updateTo()` (or `updateDynamic()`) before the tween finished. If you saved some kind of property to prevent switching, then that property would essentially be the one I am proposing.

Let me know what you think!

**Comment by sole** [comment]
@adrienbrunet what did you think?

**Comment by adrienbrunet** [comment]
Well, I'm not sure what the best option is. I proposed updateTo() because I saw it in use in another library about tweening things and it makes sens. Meanwhile, @mikebolt seems right. I think how we implement is more on the maintainer side than mine (it's been quite some time since I opened this issue, I'm not using it so often now). I just think being able to do it would be a good feature. =)

**Comment by franciscop** [comment]
Hi @adrienbrunet, I basically made a library exactly for this. It only supports CubicInOut, but it's _super_ smooth:
https://github.com/franciscop/ola/
