### ISSUE TITLE
How to get first paragraph of summary from wikipedia using javascript

### ISSUE THREAD

**Issue by marie15** [tweenjs/tween.js#261]
Hi everybody, I'm trying to get summary from wikipedia, so I ead the @gautamadude's post that is very interessting and help too much. Now I want to get only the first paragraph, I tried many attempts but I got 'honymie' tag of wikipedia, and I don't now to reùove this tag and so get the first paragraph. Any help is appreciated.

Thanks for advance

**Comment by sole** [comment]
Spam.

**Comment by marie15** [comment]
Why you close the post?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-05-09 10:17 GMT+01:00 sole <notifications@github.com>:
