### ISSUE TITLE
[idea] boolean method or property to check state on individual tweens.

### ISSUE THREAD

**Issue by trusktr** [tweenjs/tween.js#265]
This would be good because it would make it easier to use tween instances inside of other APIs, not limit the user to the Tween.js API. For example, I have code like this:

``` js
let rotationTween = new TWEEN.Tween(letterNode.rotation)
    .to({x:0, y:0, z:0})
    .start()

Motor.addRenderTask(time => {
    rotationTween.update(time)
})
```

The function passed to `Motor.addRenderTask` is executed inside the Motor's animation frame loop, which you see calls the tween instance's `update()` method. 

This works fine, but I need to be able to remove the render task when the tween is complete. Right now, the only way to do this is to write something like this:

``` js
let tweenComplete = false
let rotationTween = new TWEEN.Tween(letterNode.rotation)
    .to({x:0, y:0, z:0})
    .onComplete(() => tweenComplete = true)
    .start()

let task = Motor.addRenderTask(time => {
    rotationTween.update(time)

    if (tweenComplete) Motor.removeRenderTask(task)
})
```

It'd be nice to simply check the tween instance, like this:

``` js
let rotationTween = new TWEEN.Tween(letterNode.rotation)
    .to({x:0, y:0, z:0})
    .start()

let task = Motor.addRenderTask(time => {
    rotationTween.update(time)

    if (rotationTween.isComplete) Motor.removeRenderTask(task)
})
```

It's not a hard change, maybe I'll make a PR...

**Comment by trusktr** [comment]
This change would also include things like `tween.isStarted`, `tween.isStopped`.

**Comment by sole** [comment]
That sounds like a good idea. And it would probably make writing tests easier because you can check that the status of the objects is what you expect it to be.

Related to this change, there was another idea/feature request for emitting events in "es6-tween" i.e. tween v2 https://github.com/tweenjs/es6-tween/issues/4

I'm quite wary of introducing new features in the current version, which is why I suggested the feature in 'v2' :-/

**Comment by trusktr** [comment]
For sure. Nothing wrong with a v2. :] I'll post more ideas if I have any...

**Comment by dalisoft** [comment]
@trusktr Try this version https://gist.github.com/dalisoft/8b87519bbc54d029f7a6a576673661ec

**Comment by trusktr** [comment]
Closing this, as improvements have already been made in this area.

The original example becomes

```js
let rotationTween = new TWEEN.Tween(letterNode.rotation)
    .to({x:0, y:0, z:0})
    .start()

Motor.addRenderTask(time => {
    return rotationTween.update(time) //  if it returns false, the loop will be terminated.
})
```

because `.update()` returns `false` which in this case that imagined `Motor` API can stop the loop on a false return values (`false` returned by a `Tween` means it is finished updating).
