### ISSUE TITLE
Update individual tweens.

### ISSUE THREAD

**Issue by trusktr** [tweenjs/tween.js#268]
Seems `tween.update()` is not recommended while `TWEEN.update` is. Are there any caveats/downsides to using `tween.update(timestamp)` directly?

**Comment by mikebolt** [comment]
If you normally update tweens with `TWEEN.update()` (without a custom timestamp parameter), then you can update individual tweens by passing `tween.update` the current timestamp from `Date.now()` or the argument passed to the `requestAnimationFrame` callback. This will only update one tween, and it should work like you expect.

You can also keep track of your own "time" value and always pass that value to the update methods. However, serious problems will occur if you use different time variables for the same tween, e.g. you start a tween using a time value from a counter in a `requestAnimationFrame` callback, then you call `TWEEN.update()` with no parameters.

**Comment by trusktr** [comment]
Cool, that's what I'm doing is passing the time from my own loop. Seems to be working great!
