### ISSUE TITLE
onUpdate could return _object inteed of relying on this.

### ISSUE THREAD

**Issue by lordgiotto** [tweenjs/tween.js#270]
Hi, first of all thanks for this library :)
I'm using it in a simple smoothScrollTo class on my website: the problem is that, usually, i prefer to .bind(this) when I call a prototype function of my instance, but the case of onUpdate I can't do that, so i can access either to my instance or the value i need form your library (that returns the object with the tweened values binded to 'this').

Your decision to return _object binded to this is a precise design choice or you could consider to change this behaviour?

A little exemple to better descrive my problem:

```javascript
var ScrollAnimation = function(node) {
    this._node = node;
    this._tween = new TWEEN.Tween({scrollPos: this._getCurrentScrollPos()});
    this._tween.onUpdate(this._updateScrollPos.bind(this));
};

// Various prototype method

ScrollAnimation.prototype._updateScrollPos = function() {
    // this here is the instance of ScrollAnimation, 
    // so I can access to this._node for exemple, 
    // but I cannot access to the tweened values.
}
```

I can make a PR if you wish, but the design decision is up to you :)

**Comment by mikebolt** [comment]
Hi lordgiotto.

I definitely agree that tween.js binding the callback to the tweened object is a bit unconventional. I think the conventional way to do it would be to only pass the target object to the callback as a parameter.

Unfortunately, existing code might break if we stopped binding the target object, so it will have to stay like it is in the current version. In the next version, I would like the target object to be the first parameter to the callback, and the updated tween to be the second parameter.

I'm assuming you know a good workaround to the problem, but let me know if you need any help. I will close this issue for now.

**Comment by lordgiotto** [comment]
I completely understand, looking forward to the next version, but I'll use a workaround for now :)
Thank you!
