### ISSUE TITLE
The question about file name

### ISSUE THREAD

**Issue by kennynaoh** [tweenjs/tween.js#280]
Hello @sole ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there is a question want to ask.
There are no `Tween.js` in version `0.11.1`~`0.14.0` on [npm](https://www.npmjs.com/package/tween.js), but has `index.js`.
Are they the same file but different name?
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/8674
https://github.com/cdnjs/cdnjs/pull/8678

**Comment by sole** [comment]
Hello @kennynaoh - yes you are correct.

We used to publish a special built version of the library which was in `index.js` but now we just point to `src/Tween.js` - there's no special built version.

Hope that helps!

**Comment by kennynaoh** [comment]
Thanks!

**Comment by PeterDaveHello** [comment]
Okay, now we have tween.js on cdnjs.com, maybe we could also mention it on the readme :+1:

**Comment by sole** [comment]
@PeterDaveHello whose README? cdn's? It is not clear to me how should people use tween.js with cdnjs. If you want to suggest a change and send a PR with instructions in the style of the [existing instructions](https://github.com/tweenjs/tween.js/blob/master/README.md#more-advanced-users-might-want-to) that would be very nice of you :-)

**Comment by PeterDaveHello** [comment]
@sole sorry for the late reply, PR sent here: #285, thank you!

**Comment by mikebolt** [comment]
Looks good to me. Thanks for hosting the project!

**Comment by PeterDaveHello** [comment]
NP
