### ISSUE TITLE
Tween.end occasionally does not finish a tween

### ISSUE THREAD

**Issue by mikebolt** [tweenjs/tween.js#283]
Tween.end() has an issue caused by floating point inaccuracy errors. The problem is that `(_startTime + _duration - _startTime) / _duration` is occasionally slightly more than and occasionally slightly less than 1. In the case that it is less than 1, it will not properly complete the tween and call the onComplete callback.

When run in browsers, the two test cases that test Tween.end fail at random.

I think a good fix would be to not use Tween.update in Tween.end, but instead just set the end values and call onComplete manually.

**Comment by dalisoft** [comment]
maybe i wrong, but i have some idea.
```javascript
Tween.prototype.end = function () {
_startTime = TWEEN.now() + _duration + _delay;
return this.update(_startTime);
}
```
Check the code, then let me know works or not. I can't check, because i'm temporarily not in code-made state. Sorry :(

Thanks,
@dalisoft

**Comment by sole** [comment]
@mikebolt or we should use an epsilon comparison instead: if the difference is less than a small value `epsilon`, the comparison is true.

Do you have test cases for this? ta!

**Comment by yarivdev** [comment]
Bumping..
Great piece of software btw, thanks!

**Comment by mikebolt** [comment]
fixed
