### ISSUE TITLE
Multiple onUpdate fires

### ISSUE THREAD

**Issue by andrey-hohlov** [tweenjs/tween.js#288]
Hi!
I have first experience with Tween.js and it's make me happy, thank you.

I making something like roulette-game.

Part of code for example.

```javascript
var roulette = new Roulette(params);
$('.js-roulette-play').on('click', function () {
  roulette.play();
});
```
In Roulette method I've use Tween for make animation:

```javascript
var params = {
  rotate: curRotate
};

var rolling = new TWEEN.Tween(params);

rolling.to({rotate: targetRotate}, 5000);

rolling.onUpdate(function() {
  console.log(this.rotate);
  $roulette.css('transform', 'rotate(' + this.rotate + 'deg)');
});

rolling.onComplete(function () {
  callback();
});

rolling.start();

requestAnimationFrame(animate);

function animate(time) {
  requestAnimationFrame(animate);
  TWEEN.update(time);
}
```

Next time when I press button again onUpdate callback fire n+1 times (i see when look in console).
Callback function inside onComplete fire once.

Can you help me? What i doing wrong?

**Comment by mikebolt** [comment]
If the code that sets up the requestAnimationFrame loop is inside the
roulette.play() method, then that's your problem. You should only have one
animation loop at a time.

**Comment by andrey-hohlov** [comment]
@mikebolt thank you! I understood my mistake.

Now It's works:
```javascript
function animate(time) {
  if (this.isRolling) {
    requestAnimationFrame(animate);
  }
  TWEEN.update(time);
}
```
