### ISSUE TITLE
Memory leak or not?

### ISSUE THREAD

**Issue by trusktr** [tweenjs/tween.js#289]
After [making my accessors enumerable](https://github.com/tweenjs/tween.js/issues/267), I'm currently using Tween.js as follows, because it's easy, and haven't spent the time to investigate if I'm doing it without causing any leaks. The following is in a React component's `componentDidMount` lifecycle method:

``` js
        async componentDidMount() {
            const rocket = this.refs.rocket
            await rocket.ready

            const {position, absoluteSize} = rocket

            const rocketToEarthTween = new Tween(position)

            rocketToEarthTween.to({
                x:0,
                y:0,
            }, 2000)

            rocketToEarthTween.start(performance.now())

            const positionTask = Motor.addRenderTask(time => {
                rocketToEarthTween.update(time)

                if (position.x === 0 && position.y === 0) {
                    //rocketToEarthTween.end()
                    Motor.removeRenderTask(positionTask)
                }
            })
        }
```

I'm starting the tween, then `Motor.addRenderTask` hooks into the browser's paint cycle with `requestAnimationFrame`.

Is that fine? Or do I need to call `rocketToEarthTween.end()` to clean things up and prevent memory leaks?

**Comment by mikebolt** [comment]
You don't need to call tween.end or tween.remove unless you expect that the
tween won't be updated with a timestamp greater than or equal to its ending
time. I don't think you have that problem here. As long as removeRenderTask
removes the reference to the anonymous lambda function, then I don't see
any memory leaks here.

However, I would recommend that you put the removeRenderTask call in the
tween's onCompleteCallback, so that you don't have to check the ending
values explicitly.

**Comment by mengxun1437** [comment]
hi, tweenjs is the best engine i have used
but I notice that 

**In TWEEN.update (Group)**
![image](https://user-images.githubusercontent.com/54832685/182759788-66e7364b-d143-451e-af98-ec190688133c.png)

However in Tween's instance object, when we use update, the 'used tween animation' will not be deleted.
So if i want the lib to help me deal with memory leak, i should use TWEEN.update or Group.update, and if i use Tween instance object's update, i should remove 'used' by myself?

**Comment by trusktr** [comment]
Hello @mengxun1437 glad you like the lib! I'm not completely sure what you mean. Would you be able to provide sample code on jsfiddle or CodePen?

**Comment by mengxun1437** [comment]
> 

I'm sorry I didn't express my question clearly and caused you trouble

I wrote an example on the codepen platform, here is the link:
[https://codepen.io/mengxun1437/pen/QWmmaJo?editors=1011](https://codepen.io/mengxun1437/pen/QWmmaJo?editors=1011)

You can notice the console output,

Every time I will use a new Tween instance to achieve a piece of my animation (maybe this is not very elegant), if I use the 'update' of this instacnce in RAF to update, then the Tween instance on TWEEN (GROUP) There will be more and more, whether this will affect the performance of my application, I am not very clear about this, I hope to get your reply

Finally, I'm a newbie in 3D orientation, hope you can understand my description ability

**Comment by mengxun1437** [comment]
> Hello @mengxun1437 glad you like the lib! I'm not completely sure what you mean. Would you be able to provide sample code on jsfiddle or CodePen?

I'm sorry I didn't express my question clearly and caused you trouble

I wrote an example on the codepen platform, here is the link:
[https://codepen.io/mengxun1437/pen/QWmmaJo?editors=1011](https://codepen.io/mengxun1437/pen/QWmmaJo?editors=1011)

You can notice the console output,

Every time I will use a new Tween instance to achieve a piece of my animation (maybe this is not very elegant), if I use the 'update' of this instacnce in RAF to update, then the Tween instance on TWEEN (GROUP) There will be more and more, whether this will affect the performance of my application, I am not very clear about this, I hope to get your reply

Finally, I'm a newbie in 3D orientation, hope you can understand my description ability

**Comment by mikebolt** [comment]
Hi @mengxun1437

The codepen you wrote doesn't work for me. It doesn't call your update callback.

I recommend rewriting it without calling the tween instance's update function manually. Start by replacing line 33 like this:

```
//tween?.update()
TWEEN.update();
```

It's almost never a good idea to update a single tween manually.

**Comment by mengxun1437** [comment]
> Hi @mengxun1437
> 
> The codepen you wrote doesn't work for me. It doesn't call your update callback.
> 
> I recommend rewriting it without calling the tween instance's update function manually. Start by replacing line 33 like this:
> 
> ```
> //tween?.update()
> TWEEN.update();
> ```
> 
> It's almost never a good idea to update a single tween manually.

i am very glad that you reply to me,and i think the way  you recommend is the right way to use tween.js

i just confused that why i can not use tween instance's update, i find it can achieve the the same goal

the example in the codepen just an exapmle,so that's it doesn't work for you, i write that example case just to ask why the   
tween instances are added the global TWEEN._tweens

if the TWEEN.update will splice the completed tween,why we use the tween instance's update, the completed tween are not spliced from the global TWEEN._tweens,i think these two cases's update are not in the same standard when the tween was completed,or maybe we should splice it in tween instance's update,too?(just a suggestion)

anyway,very grateful for your reply

**Comment by trusktr** [comment]
> It's almost never a good idea to update a single tween manually.

I think it depends on use case, and in fact is a very good idea (I believe we should update docs to use groups and tweens, and avoid `TWEEN`).

The reason is because, when making _components_, as in differing parts of an app that may have their own separate animations, we want them to be in control of their own tweens, and not inadvertently updates in totally unrelated components.

Using `TWEEN` by multiple components is similar to using a shared global state by multiple components, and if they do not know what each are doing, it can lead to things not working.

I recommend using

- individual `Tween` instances for single-tween animations
- `TWEEN.Group` for animations involving multiple tweens (f.e. `.chain`ed tweens)
- and `TWEEN` only when the app is small and self-contained (like the whole app is a simple component by itself).

and that in a breaking change we should set [this line](https://github.com/tweenjs/tween.js/blob/9f8c56c4d5856a970b45895bb58cd9d1d56cf3ea/src/Tween.ts#L50) to default to `false`, possibly add a `true` option that restores adding to the default group, and otherwise require people to use tweens or Groups directly.

This is the only way to ensure robust multi-component development, while a shared global is not the ideal way to achieve that (without more complicated modifications to `Group` like perhaps adding labels for tween, or something, but simply not adding to a default group is the simplest code change).

Note that currently, to avoid unintended interference of a component's tween by outside/unexpected manipulation of `TWEEN`, the tween should be instantiated with the second arg as `false` or a group instance:

```js
const tween = new TWEEN.Tween(obj, false) // it will not be added to the TWEEN group
```

---

@mengxun1437  On the following line, `tween` is being set to `undefined`:

```js
  tween = generateTween()
```

because `generateTween` does not return anything.

Here's a working demo: 

https://codepen.io/trusktr/pen/wvmjwwQ/536097270aeea3d13ccf286931369409?editors=0011

**Comment by mengxun1437** [comment]
@trusktr 
Your reply helps me a lot, i get what you mean! 
Thanks!
