### ISSUE TITLE
Implement onBeforeRepeat

### ISSUE THREAD

**Issue by shelbeniskb** [tweenjs/tween.js#290]
is it possible to offer onRepeat? I need to change some state before the repeat cycle start, so I onRepeat is necessary, I also find TweenMax offer this function.

**Comment by sole** [comment]
Could you define a bit better how 'onRepeat' would work? Would it be executed before each repeat cycle? Would it maybe be better called `onBeforeRepeat`?

**Comment by dalisoft** [comment]
I like `onBeforeRepeat` and `onBeforeReverse`. Very good naming.

**Comment by shelbeniskb** [comment]
@sole `onBeforeRepeat` will be an chance for developer to change some state or value, for example,
move a picture from A to B,  we can change the picture before the next repeat happens.

**Comment by sole** [comment]
Ok, makes sense. I will update the title of the issue to reflect this :)

**Comment by dalisoft** [comment]
@shelbeniskb Maybe you looking for [that](https://github.com/tweenjs/es6-tween/blob/master/dist/Tween.js#L1055)? It implements `repeat and reverse` events, you can define via `tween#on('reverse', (object) => { console.log(object); })`

**Comment by trusktr** [comment]
An `onRepeat` feature has since been added. If that's not enough, definitely feel free to reply and we can re-open of make a new issue. :)
