### ISSUE TITLE
Tween.js:75 Uncaught TypeError: Cannot read property 'window' of undefined

### ISSUE THREAD

**Issue by ebdrup** [tweenjs/tween.js#292]
![image](https://cloud.githubusercontent.com/assets/899914/19021628/757dbdcc-88c6-11e6-95d4-e737de0ab411.png)

Can't figure out why I'm getting this. I just include Tween.js raw in my bundle. Maybe a guard could bedded checking that `this` is not undefined?

I'm on Chrome Version 53.0.2785.116 (64-bit)

**Comment by mikebolt** [comment]
I think I fixed that issue in this commit:

github.com/tweenjs/tween.js/commit/002c1d99f50d99a2c100687079db3e7760222c02

Please get the latest Tween.js directly from GitHub and see if you still
get the error.

**Comment by ebdrup** [comment]
I am using the latest one. With the this-solution. I've npm installed it.

**Comment by sole** [comment]
Did you install it using `npm install https://github.com/tweenjs/tween.js.git` or just `npm install tweenjs`?

The latter might not reflect the latest in the github repo-sometimes there is a lot of caching.

**Comment by Thristhart** [comment]
Ran into this problem, found this issue, switched to installing from github (via `npm install tweenjs/tween.js`) and that resolved the problem.
