### ISSUE TITLE
parseFloat second argument

### ISSUE THREAD

**Issue by hendrysadrak** [tweenjs/tween.js#295]
I have a question, why is there a second argument passed to parseFloat, if it only accepts one parameter?

http://stackoverflow.com/questions/8555649/second-argument-to-parsefloat-in-javascript
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt

**Comment by dalisoft** [comment]
`parseFloat` is accepts two parametr (argument) as i know.
Like
```javascript
var blue = '#00ccff';
var toHex = parseFloat('0x' + blue.substr(1), 16) // or parseInt
console.log(toHex) // it's converts 16-bit (hex) to 10-bit (dec) numbers
```
And this is just example, there maybe has bugs/issues

**Comment by hendrysadrak** [comment]
parseFloat doesn't work that way, the code example u gave logs `0`. With parseInt you can convert between bases, but parseFloat does not use the second argument for anything. Check the links above.
```
console.log(parseFloat("0xff00ff", 10));
console.log(parseFloat("0xff00ff", 16)); 
// both output zero, though 0xff00ff decimal value is 16711935
```

**Comment by dalisoft** [comment]
Ok, sorry for wrong info. I remember it for prevent mistakes about parseFloat

**Comment by sole** [comment]
@hendrysadrak What? Where?

**Comment by hendrysadrak** [comment]
@sole https://github.com/tweenjs/tween.js/blob/master/src/Tween.js#L130

**Comment by sole** [comment]
@hendrysadrak thank you. Yep, sounds like a bug. Thanks for spotting!

Would you mind sending a PR? =)

**Comment by mikebolt** [comment]
I fixed this earlier: https://github.com/tweenjs/tween.js/commit/b5c08f323f264d66d6af8b9e203b52b8dbce1593
