### ISSUE TITLE
Tween.js and CreateJS/TweenJS. What are different?

### ISSUE THREAD

**Issue by whatisor** [tweenjs/tween.js#298]
I am confusing with 2 versions of Tweenjs. There are two APIs.

**Comment by mikebolt** [comment]
They are unrelated except that they have the same name and they are both
intended for the same purpose!

I don't know what is different specifically. I have not used the other
Tween.js.

**Comment by whatisor** [comment]
Thank you. I see. I always use Tween.js,too.
It is terrible same name.
