### ISSUE TITLE
Using `prototype` instead of `this`

### ISSUE THREAD

**Issue by dalisoft** [tweenjs/tween.js#300]
Hi @mikebolt, @sole 
I interesting in performance improvement of using `prototype` insteadof `this` access/write.

You can see and compare perf with <a href="https://github.com/dalisoft/tweenjs-tiny">Tiny my js</a> or <a href="https://github.com/dalisoft/SuperAnimation.js">bit extended tween.js</a>.

Let me know about performance improvement

http://stackoverflow.com/questions/3493252/javascript-prototype-operator-performance-saves-memory-but-is-it-faster

**Comment by sole** [comment]
With prototype you 'refactor' methods into the prototype instead of creating them in each instance with 'this access/write' as you call it.

If you could provide a direct comparison rather than links to projects that would be more helpful to take decisions.

**Comment by dalisoft** [comment]
I think there very good performance already
