### ISSUE TITLE
Continuous animation

### ISSUE THREAD

**Issue by Zergus** [tweenjs/tween.js#301]
Is this the proper way to define continuous animation:
```
var tween = new TWEEN.Tween({x: 0, y: 0, z: 0})
    .onUpdate(function () {
        //something
    });

setInterval(function () {
    tween.to(smth.getNewCoordinates()).start();
}, 1000);
```

Or should I stop animation as soon as new coordinates appeared?

Thanks a lot!

**Comment by mikebolt** [comment]
You should never need to use setInterval, but go ahead if it works for you.

You can chain tweens together like this:

    tweenA.chain(tweenB);

Now tweenB will automatically start whenever tweenA finishes. You can also do this by starting another tween within an onComplete callback:

    tweenA.onComplete(function() {
        tweenB.start();
    });

If you want to repeat a single tween forever, you can use the repeat function.

    tweenA.repeat(Infinity);

All of this information is in the ["Controlling a Tween" section of the user guide](https://github.com/tweenjs/tween.js/blob/master/docs/user_guide.md#controlling-a-tween).

You probably don't need to remove a tween. Tweens remove themselves (as in, they stop doing anything) when they finish. Also, there is currently a bug if you remove a tween in a callback.

**Comment by Zergus** [comment]
Yes, I got it. But how to manage `.to()` if arguments should change pretty often? I mean I need to reload `.to(coords)` each time `coords` changed. Should I just use link to object that changes on itself and set `Infinity` ?

**Comment by Zergus** [comment]
Well, this works for me:

```

this.seekAnim = new AFRAME.TWEEN.Tween(this.el.getAttribute('rotation'))
                .to(this.newCords, duration)
    			.easing(AFRAME.TWEEN.Easing.Linear.None)
    			.onUpdate(function () {
    				el.setAttribute('rotation', { x: this.x, y: this.y, z: this.z });
    			})
                .repeat(Infinity)
                .start();

// somewhere else
Object.assign(this.newCords, this.CAMERA.getAttribute('rotation'));

```

**Comment by UrosCvijanovic** [comment]
If I use the global TWEEN.update() this animation works fine. But if I use the group and update it in this way the animation is not working. Why is this the case as the Tween js documentation is suggesting this implementation?

private warningBlinkingWithInterval(seconds) {
        let tweenGrp = new TWEEN.Group();
        let delta = this.clock.getDelta();
        let blink = Math.floor(this.timeSec1 / seconds) & 1;
        let isBlink = Boolean(blink);
        console.log(isBlink);
        if (this.previousFrameBlinked !== isBlink) {
            if (isBlink) {
                this.warningHarnesses.forEach(harn => {
                    let resizeCircleUp = new TWEEN.Tween(harn.children[4].scale, tweenGrp).to({ x: 1, y: 1 }, seconds * 1000).easing(TWEEN.Easing.Quadratic.InOut).start();
                });
    
            } else {
                this.warningHarnesses.forEach(harn => {
                    let resizeCircleDown = new TWEEN.Tween(harn.children[4].scale, tweenGrp).to({ x: 0.2, y: 0.2 }, seconds * 1000).easing(TWEEN.Easing.Quadratic.InOut).start();
                });
            }
        }
        //console.log(tweenGrp.getAll());
        this.previousFrameBlinked = isBlink;
        this.timeSec1 += delta;
        tweenGrp.update();
    }
