### ISSUE TITLE
Cannot convert object to primitive value

### ISSUE THREAD

**Issue by enriko-riba** [tweenjs/tween.js#306]
`// Set all starting values present on the target object
    for (var field in object) {
        _valuesStart[field] = parseFloat(object[field], 10); // <-- Uncaught TypeError: Cannot convert object to primitive value
    }`

Happens atm if tweening the position of PIXI.js Text object.
field = "_events", object = Text {_events: Events, _eventsCount: 0, tempDisplayObjectParent: null, transform: TransformStatic, alpha: 1…}

But this is a generic issue and can happen with any sort of objects.

BTW why are all props cached in _valueStart? Wouldn't it be enough to cache only the tweened props?

**Comment by mikebolt** [comment]
Please update to the newest version on GitHub and test it again.

**Comment by enriko-riba** [comment]
That solved the issue, thank you.
