### ISSUE TITLE
update's bug

### ISSUE THREAD

**Issue by nickli** [tweenjs/tween.js#309]
while (i < _tweens.length) {
                /* old 
		if (_tweens[i].update(time) || preserve) {
			i++;
		} else {
			_tweens.splice(i, 1);
		}
		*/

                //new code
                //in real world, tween.update has chance to remove itself, so we have to handle this situation.
                //in certain cases, onUpdateCallback will remove instances in _tweens, which make _tweens.splice(i, 1) fail
                //@litao.lt@alibaba-inc.com

		var _t = _tweens[i];
            var _updateRes = _t.update(time);
		if( !_tweens[i] ){
		    break;
		};
                if ( _t === _tweens[i] ) {
			if ( _updateRes || preserve ) {
				i++;
			} else {
  			       _tweens.splice(i, 1);
			}
		}

	}

**Comment by mikebolt** [comment]
Yes, this is a known issue: https://github.com/tweenjs/tween.js/issues/264

I have implemented a possible fix for this issue but I have not tested it yet. If you can avoid removing tweens within an onUpdate or onComplete callback, then you will not be affected by this issue.

**Comment by nickli** [comment]
Yes, I modified the Tween.js code in the project has been tested to fix the bug in the onUpdateCallback and in the onCompleteCallback remove it self, the situation is the same in response to Tween.update, if found themselves Has been deleted, it should not be implemented i ++ and _tweens.splice (i, 1) operation, the code at the same time I repair the above two cases. In addition to your version of the code which repair? I can take over the test, I am a good local reproduction

**Comment by nickli** [comment]
In this while loop, save the current tween instance as _t var _t = _tweens [i];

Then in this instance of the tween update after the implementation of var _updateRes = _t.update (time);

  If (_t === _tweens [i]) is true, we do not need to do anything, otherwise it will hurt the innocent,

If this time the current tween.elapsed <1, then i will lead to the next tween the update will not be implemented.

If the current tween.elapsed == 1, then _tweens.splice (i, 1) is the next to delete a tween, which is the biggest problem.

**Comment by nickli** [comment]
@mikebolt  Please see my reply to the above, and if you have fixed the problem, please tell me in which version, I need to clone the latest code in the project. I have to be local tween.js and the official line.

**Comment by nickli** [comment]
@mikebolt   Or give me your repair code, I ran in the local project to see if I can solve the problems encountered

**Comment by nickli** [comment]
@mikebolt  [https://github.com/nickli/tween.js/blob/master/examples/test_for_issue309.html](https://github.com/nickli/tween.js/blob/master/examples/test_for_issue309.html)

I built a simple test html, you can see
