### ISSUE TITLE
Test using tween.js in a WebWorker

### ISSUE THREAD

**Issue by dalisoft** [tweenjs/tween.js#317]
Hi.
Can i use tween.js in Worker and How?

Thanks

**Comment by csprocket777** [comment]
Did you ever figure this out? I'm trying to do the same exact thing. I have the library available but everything only fires once.

**Comment by mikebolt** [comment]
Hi @csprocket777. Can you provide some code or explain how you are using tween.js within a WebWorker?   I would be glad to diagnose the problem or help you engineer a solution.

**Comment by mikebolt** [comment]
An issue that prevented this library from working in a WebWorker was fixed, but we have not tested that it actually works.

**Comment by dalisoft** [comment]
I'm tested this year ago with replacing some keywords (window to self, as already given) and worked good.
This feature needs only for AI/WebGL users which need very complex computations and depend on tweening.

You can close issue if you want, my issue was solved with other reason (if i'm write it here, will look like adversiting), but forgot to close issue (Sorry).

**Comment by mikebolt** [comment]
Great. Thanks for the help.
