### ISSUE TITLE
Animation doesnt work on iphone4

### ISSUE THREAD

**Issue by cruzlutor** [tweenjs/tween.js#318]
I have this issue with my iphone 4, the animations doesnt work, the element jump without transition

Here is an issue video: https://www.youtube.com/watch?v=NGyObJzTc_M
You can see other game with the same problem here: http://cruzlutor.com/games/soccer21/

**Specs**
Chrome version 47.0.2526
IOS version 7
Tween version 16.3.5

**Code**
```
/**
   * Start RAF loop
   */
  start(){
    requestAnimationFrame(this.loop.bind(this))
  }

  /**
   * Main game loop
   * @return {none} 
   */
  loop(time){
    requestAnimationFrame(this.loop.bind(this))
    if( !this.scene.current || this.scene.current.loaded === false || this.isPaused()) return false
    TWEEN.update(time)
    this.scene.update()
  }
```

**Update**
On safari happens the same

thanks

**Comment by cruzlutor** [comment]
I solved the issue today, the problem was the time parameter from RAF, I just remove the time parameter and works fine

**Comment by mikebolt** [comment]
OK. I'm glad that works.

This issue is mysterious. My best guess is that the browser passes a 'time' value in microseconds instead of milliseconds, causing tweens to happen 1000 times faster.

Good luck with your game!
