### ISSUE TITLE
Minimum browser versions? (i.e. minimum IE version?)

### ISSUE THREAD

**Issue by trusktr** [tweenjs/tween.js#324]
Hi all, what are your thoughts on, f.e., supporting only IE11+?

This would allow us to use `WeakMap` for private properties on the `Tween` class, and then we can store public methods on the prototype.

**Comment by dalisoft** [comment]
Minimum browser support still is important as some of peoples (including me) uses starts at: IE9 or higher, Android 4.2 (doesn't support WeakMap, but can be polyfilled), iOS9+ (no problemo here as Apple cared about it's) and Chrome 15+ (there too no problemo)

**Comment by dalisoft** [comment]
Can you share idea for class? Maybe i am implement it in ES6 version. Thanks

**Comment by trusktr** [comment]
@dalisoft I'll make a PR soon, so you can see what it looks like.

**Comment by trusktr** [comment]
@dalisoft Alright, here's a PR: https://github.com/tweenjs/tween.js/pull/325, all tests passing.

Instead of a private WeakMap and doing `_(this).privateMember` to access, we could just store things on this with the underscore convention and access like `this._privateMember`, but then the functionality is different in that the end user _can_ access private variables if they aren't following conventions. But the underscore method would make this continue to work in older IE.

**Comment by trusktr** [comment]
Oh, wait, `Object.assign` support starts in Edge. According to this, IE 11 has WeakMap: https://docs.microsoft.com/en-us/scripting/javascript/reference/weakmap-object-javascript

**Comment by trusktr** [comment]
How do you feel about just using the underscore convention?

**Comment by trusktr** [comment]
Here's another PR that uses the underscore method: https://github.com/tweenjs/tween.js/pull/326

**Comment by trusktr** [comment]
There we go, removed `Object.assign` in both PRs, so the underscore-convention PR works in IE9.

**Comment by mikebolt** [comment]
I am fine with the underscore convention for private variables.

**Comment by trusktr** [comment]
Closing, let's eventually add a transpile step that can support older browsers.

**Comment by trusktr** [comment]
Hey ya'll! I'm circling back to this, and would like to make some improvement and also fix some long-standing bugs.

What are the oldest browsers we need to support?
