### ISSUE TITLE
Document how releases happen

### ISSUE THREAD

**Issue by sole** [tweenjs/tween.js#328]
Right now releases happen automatically if tests pass. @sole knows this but no one else does. Sole must explain this in writing.

**Comment by trusktr** [comment]
@sole What do you run from command line to get the semantic-release started? Or, is that automatic from Travis?

**Comment by sole** [comment]
@trusktr when the tests run successfully travis triggers semantic-release which will package and publish the release if required: https://github.com/tweenjs/tween.js/blob/master/.travis.yml#L16

**Comment by dalisoft** [comment]
I have simple and small helpful (i think, maybe not) guide to how i am implemented @semantic-release in @tweenjs/es6-tween

Steps:
1. Register on Travis CI (if not yet installed).
2. Add project (if you maintain) or ask from author to permit access you (if you not owner)
3. Add script to `.travis.yml`
```bash
after_success:
  - npm run semantic-release
```
4. Edit `package.json`
```javascript
{
	...
	"directo
	"scripts": {
		...
		"semantic-release": "semantic-release pre && npm publish && semantic-release post --owner=sole --user=dalisoft" // for avoid Travis CI and @semantic-release erros, i did this trick
	},
	"repository": {
		"type": "git",
		"url": "git+https://github.com/tweenjs/es6-tween.git" // only git+https works well for me
	},
	"release": {
		"branch": "master" // your working branch
	},
	"homepage": "YOUR_HOMEPAGE_URL",
	"devDependencies": {
		...
		"semantic-release": "latest"
	},
}

```

5. Go-to Travis CI
6. Select project, eg, es6-tween
7. Press "More options" on right corner
8. Scroll down until you see `Environment Variables`
9. Add tokens with `GH_TOKEN` and `NPM_TOKEN`, but for both envs should be hidden for security reason (`Display value in build log` should be `Off`)
10. Commit you changes.
11. Then trigger @semantic-release by changing some file for better.

Good luck.
I did these steps for implementation

**Comment by sole** [comment]
OK I wrote the start of a guide for contributors, and started by documenting this. Let me know how does it look! @trusktr? @dalisoft? :-)

@dalisoft - I used your guide as the base to write the 'manual' way of adding semantic release to a project. Thank you! But I do not know where did you get the GH and NPM tokens, do you remember? I set up `semantic-release` so long ago that I do not remember if these were generated with the CLI tool.

**Comment by dalisoft** [comment]
NPM token can get via npmjs site dashboard tokens tab.
GitHub token can too can be generated via setting  -> personal access token and generate new or use existing if you know code.

Then set via Travis CI repo setting with setting ENVoriment like GH_TOKEN and NPM_TOKEN. Sorry for mistake texts if has.

**Comment by dalisoft** [comment]
Both github and npm tokens gets via site. I am not know how to get with CLI

**Comment by dalisoft** [comment]
I not sure it is required as tweenjs already configured. Or this just for developers that want implement semantic-release in own repo?

**Comment by sole** [comment]
@dalisoft ah, that's perfect re: the tokens. I might add links from the guide.

The idea is that if the process needs to be redone or if something needs to be changed, it's written there. Also if semantic-release needs to be added to another (new) repository we will know how to do it :)

**Comment by dalisoft** [comment]
@sole okay, i forgot to note that tokens are not required if you maintainer. Example, you can run semantic release without tokens as Travis CI automatic gets tokens.
Second thing, now no need manually build if build requires as prepublish takes care of this. Peoples can commit to source and everything is automatized. Thanks to you for created and continueing tweenjs
