### ISSUE TITLE
Memory footprint reduction opportunities

### ISSUE THREAD

**Issue by mikebolt** [tweenjs/tween.js#340]
Objects and arrays have a larger footprint than basic types, even when they are empty. For this reason, we could have a 10-20% memory footprint reduction by removing the initialization of _chainedTweens and _valuesStartRepeat. Some refactoring would be required. _chainedTweens could initially be null, then set to an array when 'chain' is called.

**Comment by trusktr** [comment]
Great idea! I will merge this into #538
