### ISSUE TITLE
Updating one tween at a time, not all tweens.

### ISSUE THREAD

**Issue by shelbeniskb** [tweenjs/tween.js#347]
if I invoke TWEEN.update()  multiple times, what will happen?

for examples:

componentA use  TWEEN to animate some property, 
componentB also use TWEEN to animate some property,

the two components(used in the same page) both invoke TWEEN.update() in their own loop，
but for requestAnimationFrame, TWEEN.update() will be invoked two times,

will they affect each other?

**Comment by mikebolt** [comment]
Yes, it will call onUpdate twice for each tween. The new tween group code
should fix this. We can help you test the new version. Are you using
a-frame?

**Comment by shelbeniskb** [comment]
'The new tween group code' means what?

**Comment by shelbeniskb** [comment]
@mikebolt 
I find  `npm install @tweenjs/tween.js`, it's new version?

**Comment by mikebolt** [comment]
Npm does not have the latest version yet. The fix for this issue is in the
pull request #346.

Here is the source file from alexburner's fork:
https://github.com/alexburner/tween.js/blob/master/src/Tween.js

**Comment by viperscape** [comment]
Just jumping in here, but does this library support calling update on a single tween?
```javascript
let tween = new Tween.Tween(pos)
            .to(next_pos, 1000)
            .onUpdate(function() { })
            .onComplete(function() { })
            .start();

tween.update(); // calling it directly on tween
```

**Comment by trusktr** [comment]
We should get rid of the global TWEEN group. It is a source for error (as seen here), and if people want groups, they can do it explicitly. What do you think @mikebolt ?

@shelbeniskb In the mean time, you can run `update` on individual tweens directly, for example, you create a tween for each of your components:

```js
// component 1
const tween1 = new Tween({...})
  .to(..)
  // etc
  .start()


// component 2
const tween2 = new Tween({...})
  .to(..)
  // etc
  .start()
```

then you can update them individually. For example, in a loop, you can call update on each one manually:

```js
requestAnimationFrame(time => {
  // inside of component 1
  tween1.update(time)

  // inside of component 2
  tween2.update(time)
})
```

See what I mean? Just call each component's tween's update method, not `TWEEN.update()`.

(Globals are a bad idea and don't help with modular code.)

**Comment by trusktr** [comment]
You might have a list of components, so you can loop on them:

```js
requestAnimationFrame(time => {
  for (const component of componentsList) {
    component.tween.update(time)
  }
})
```

**Comment by trusktr** [comment]
Closing, as there's no issue here. I'll make a new issue to discuss removing the global group: https://github.com/tweenjs/tween.js/issues/374
