### ISSUE TITLE
semantic-release failing in travis, new builds not published to npm in the meantime

### ISSUE THREAD

**Issue by sole** [tweenjs/tween.js#348]
For reasons unknown, semantic-release is failing:

```bash
semantic-release ERR! init No github token specified. ENOGHTOKEN
semantic-release ERR! init No npm token specified. ENONPMTOKEN
```

Mysteriously, the two variables *are* in the settings, so I don't know why it's failing.

I don't have much time to investigate this right now, but I wanted to log it so people can see we know about this

**Comment by sole** [comment]
Urgh, so first as 'emergency relief' I did a manual publish following the instructions in [this previous bug](https://github.com/tweenjs/tween.js/issues/312#issuecomment-275456563). This bumped the package to 16.8.0 and npm has it now. So everything that was on master is in npm now. 

But then I looked at the logs, it seems that there has been some sort of change in Travis CI recently. [For security reasons it won't add the encrypted tokens to pull requests coming from another repository](https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions). So all the PRs that @mikebolt was getting merged were not getting published because Travis was not adding the tokens, therefore semantic release couldn't run.

Then I created a branch in the main repo and [a PR to fix a typo in README.md](https://github.com/tweenjs/tween.js/pull/351) using that branch, and merged this PR. I was very hopeful that this would work with semantic-release... but it didn't! Now it's npm that is complaining:

```
npm ERR! publish Failed PUT 401

npm ERR! Linux 4.8.12-040812-generic

npm ERR! argv "/home/travis/.nvm/versions/node/v6.11.0/bin/node" "/home/travis/.nvm/versions/node/v6.11.0/bin/npm" "publish"

npm ERR! node v6.11.0

npm ERR! npm  v2.15.12

npm ERR! code E401

npm ERR! You must be logged in to publish packages : @tweenjs/tween.js

npm ERR! 

npm ERR! If you need help, you may report this error at:

npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:

npm ERR!     /home/travis/build/tweenjs/tween.js/npm-debug.log

npm ERR! Linux 4.8.12-040812-generic

npm ERR! argv "/home/travis/.nvm/versions/node/v6.11.0/bin/node" "/home/travis/.nvm/versions/node/v6.11.0/bin/npm" "run" "semantic-release"

npm ERR! node v6.11.0

npm ERR! npm  v2.15.12

npm ERR! code ELIFECYCLE

npm ERR! @tweenjs/tween.js@0.0.0-development semantic-release: `semantic-release pre && npm publish && semantic-release post`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the @tweenjs/tween.js@0.0.0-development semantic-release script 'semantic-release pre && npm publish && semantic-release post'.

npm ERR! This is most likely a problem with the @tweenjs/tween.js package,

npm ERR! not with npm itself.

npm ERR! Tell the author that this fails on your system:

npm ERR!     semantic-release pre && npm publish && semantic-release post

npm ERR! You can get information on how to open an issue for this project with:

npm ERR!     npm bugs @tweenjs/tween.js

npm ERR! Or if that isn't available, you can get their info via:

npm ERR! 

npm ERR!     npm owner ls @tweenjs/tween.js

npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

npm ERR!     /home/travis/build/tweenjs/tween.js/npm-debug.log

Done. Your build exited with 0.
```

I don't have more time to research this now, if anyone has any ideas I'll be happy to read them after the week-end :-)

Sorry!

**Comment by dalisoft** [comment]
@sole I see there same issue as my fork. @mikebolt should own token to Travis CI to verify that has access after you grant access. Without removing old token can be added new without displaying values. I am fixed with that way

**Comment by rantrix** [comment]
I think the tokens that was created from using `semantic-release-cli` probably expired. You just need to re-run `semantic-release-cli setup` for it to add new tokens, then remove the old tokens from your accounts.

**Comment by trusktr** [comment]
Looking to fix this.

**Comment by trusktr** [comment]
@mikebolt I think this is the highest priority ticket. We really should fix this so we can get new features published properly. I haven't had a chance to look yet, but this will be the next thing I look at when I get back here. If you're working on Tween.js, if you can please work on this before anything else that'd be super great!

**Comment by mikebolt** [comment]
The latest build in Travis CI emitted this error:

````
The npm token (https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) configured in the NPM_TOKEN environment variable must be a valid token (https://docs.npmjs.com/getting-started/working_with_tokens) allowing to publish to the registry https://registry.npmjs.org/.
If you are using Two-Factor Authentication, make configure the auth-only level (https://docs.npmjs.com/getting-started/using-two-factor-authentication#levels-of-authentication) is supported. semantic-release cannot publish with the default auth-and-writes level.
Please make sure to set the NPM_TOKEN environment variable in your CI with the exact value of the npm token.
````

**Comment by mikebolt** [comment]
I think it is fixed now. I think what happened is that sole's npm token became invalid after they added 2FA. Then there was another issue. My manually npm published versions didn't have releases and tags in the format "v1.2.3", so semantic-release published releases with incorrect 16.x version numbers. This was fixed by manually renaming (relabeling?) those releases.

If semantic-release stops working and you need a release you can message me and I will release it manually.

Please remember to use [semantic release prefixes](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits) on every commit. I will add some instructions in the docs then look into automatically enforcing the commit message format.
