### ISSUE TITLE
Changing the Tween on the fly

### ISSUE THREAD

**Issue by AndyNormore** [tweenjs/tween.js#355]
I have an issue regarding performance.

`
TWEEN.remove(object_sprite);
								
									var tween_objects = new TWEEN.Tween(object_sprite)
										.to({ x: object_new_x, y: object_new_y}, ANIMATION_DELTA)
										.onUpdate(function() {
											//console.log(this.x, this.y);
										})
										
										.onComplete(function() {
											
										})
										.start();`

So I'm expecting the tween to be removed, however, my browser severely starts to drop in FPS after a few minutes of running.

What's the correct solution here? It doesn't seem like remove() is doing anything.

**Comment by mikebolt** [comment]
TWEEN.remove only accepts a tween. It looks like you might be passing in
the object that was the target of a tween instead of the actual tween.

**Comment by AndyNormore** [comment]
So then can't I just call TWEEN.removeAll(); from.. ANYWHERE in my code? This doesn't seem to improve things either.

If I remove this tween_objects code, my app runs 100% smooth forever. So again, I believe that the tweens are stacking, stacking, stacking, and melting the CPU

**Comment by mikebolt** [comment]
Okay, I will look into this later.

**Comment by AndyNormore** [comment]
I'll leave you some code.

`function animationLoop(){

player_ship = Posts.findOne({type:"ships", fleet_status:"selected"}); 
if(player_ship){

var tween_objects = new TWEEN.Tween(object_sprite)
	.to({ x: object_new_x, y: object_new_y}, ANIMATION_DELTA)
	.onUpdate(function() {
		//console.log(this.x, this.y);
	})
	
	.onComplete(function() {
		
	})
	.start();


`

**Comment by AndyNormore** [comment]
Sorry I don't think this is a problem with your code at all. I tried another tween engine with the exact same result. Doing a trace log shows that I'm rebuilding these tweens 30 times a second, so even if removeall is working, my cpu will lag down.

I'll move the tween loop out of the render loop, and that should fix it! Duhhh.

Cheers, and thanks for the lib. Come by and say hello on SCO :)

**Comment by AndyNormore** [comment]
Just wanted to confirm this as fixed, moved it out of my main render loop to an interval loop of 5 seconds and it works perfectly. Thanks again.
