### ISSUE TITLE
Find easier solution to packaging and publishing

### ISSUE THREAD

**Issue by sole** [tweenjs/tween.js#357]
Right now we're using semantic-release on Travis and it's producing issues such as #348.

I'm starting to think that maybe a more reliable/explainable/debuggable solution is to have a sort of script that a maintainer can run in their computer, and that generates the release (in GitHub, with the tags and everything) and publishes it to npm.

How does the idea sound? As much as I love semantic-release, I feel that running it on Travis causes more issues than it helps with.

**Comment by mikebolt** [comment]
This would be great. I would like to make a new release with the current
version of master. I think I can handle the version numbers manually.

**Comment by mikebolt** [comment]
Here's my npm profile if it helps: https://www.npmjs.com/~mikebolt

**Comment by sole** [comment]
Thank you @mikebolt! I added you to the @tweenjs org - let me know if you cannot publish.

My intention behind having an 'automated' process was to make the decision process of version numbers faster, but of course we can use a manual approach in the meantime.

In the past I was quite 'brutal' and would just update the major version each time I did a release 🤓

**Comment by mikebolt** [comment]
It looks like the old npm repo is about 10x as popular, in terms of downloads. Should we try to get people to switch to the new one, or update both npm repositories?

**Comment by iangilman** [comment]
Is this why npm still has 16.6.0 when here it's at 17.1.0? I've just run into a bug that appears to be fixed in 17.1.0, so I'd love to grab the latest, but I'm using npm + webpack, so it's not so easy to switch over to cdnjs or something...

**Comment by mikebolt** [comment]
Looks like npm has 17.1.0 now. @sole I will try to npm publish next time I
make a release.

**Comment by iangilman** [comment]
@mikebolt Huh... I swear I saw 17.1.0 on the npm page for a second yesterday, but now it's back to 16.6.0. This is the page I'm looking at: 

https://www.npmjs.com/package/tween.js

...and this is what I see:

<img width="297" alt="image" src="https://user-images.githubusercontent.com/338989/30446307-9c66559c-993d-11e7-8fb7-6b49abadba80.png">

...and this is what I get from `npm install`:

```
npm ERR! notarget No compatible version found: tween.js@^17.1.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 16.6.0, 16.5.0, 16.4.0, 16.3.5, 16.3.4, 16.3.3, 16.3.2, 16.3.1, 16.3.0, 16.2.0, 16.1.1, 16.1.0, 16.0.0, 15.0.0, 0.14.0, 0.13.0, 0.12.0, 0.11.0
```

Any idea what's going on?

**Comment by mikebolt** [comment]
Oh right, we have two different npm repositories. The first will be used
going forward. We should set up one of those "this package has moved"
notices for npm.

new: https://www.npmjs.com/package/@tweenjs/tween.js

old: https://www.npmjs.com/package/tween.js

**Comment by iangilman** [comment]
Oh, I see! Yes, that was confusing. 

It's a shame you have to go with `@tweenjs/tween.js` instead of the easier to remember `tween.js`... is there some way to sort that out?

Anyway, I've got what I need; thank you for the help!

**Comment by sole** [comment]
Hmm, I don't remember why I really wanted to move from /tween.js to @tweenjs/tween.js - Something something about all being under the @tweenjs umbrella and making sense.

I added Mike to the 'old package'. It is currently marked as deprecated, so people should already get a warning to go and install the new one, but feel free to un-deprecate. Sorry it is confusing people so much 😔

**Comment by mikebolt** [comment]
I think deprecation is appropriate. I will add a big warning and a link in
the old README.
