### ISSUE TITLE
@tweenjs/tween.js v16.8.0 missing changes from v16.7.1

### ISSUE THREAD

**Issue by siwel** [tweenjs/tween.js#358]
Hey,

https://github.com/tweenjs/tween.js/issues/348 would suggest that @tweenjs/tween.js v16.8.0 should have the changes made in master up to that point. However looking at the code that downloads when installing it is an outdated version.

Is it currently possible to get version 16.7.1 on npm?

Thanks,
Lewis

**Comment by mikebolt** [comment]
What features are missing in 16.8.0? Could you find the commit id for version 16.8.0?

**Comment by mikebolt** [comment]
You might have 16.6.0. Check the file node_modules/tween.js/package.json for the version number. Actually, if you have the correct repo it will be in node_modules/@tweenjs/tween.js/package.json .

Use this command:

    npm i @tweenjs/tween.js

**Comment by siwel** [comment]
Hey,

Just double checked with a fresh install, node_modules/@tweenjs/tween.js/package.json show's that I'm  on 16.8.0

![image](https://user-images.githubusercontent.com/6073481/28358423-b6017e0e-6c66-11e7-885e-a700792ad629.png)

However, I'm still outdated code in node_modules/@tweenjs/tween.js/src/Tween.js, for example, _tweens variable is an array, where as in master it is an object;

![image](https://user-images.githubusercontent.com/6073481/28358862-5c07ce92-6c68-11e7-8fa1-cf482ffa2ab5.png)

And I'm still seeing issues such as https://github.com/tweenjs/tween.js/issues/337

Thanks,
Lewis

**Comment by mikebolt** [comment]
Ok, thanks for the info. I will try to get a new version on npm.

**Comment by siwel** [comment]
Great, Thanks very much :)

**Comment by mikebolt** [comment]
Please try version 16.9.0 from npm.

**Comment by siwel** [comment]
Awesome - seeing the correct code now. Thanks for getting this sorted 👍
