### ISSUE TITLE
assignDeep has a bug

### ISSUE THREAD

**Issue by shelbeniskb** [tweenjs/tween.js#360]
it seems a [bug](https://github.com/tweenjs/tween.js/blob/master/src/Tween.js#L135) here 

after assign `sourceProto` to `targetProto`, it also change the `Object.prototype`!!!

`Object.prototype` also has  `add` `getAll` `remove` `removeAll` `update`

it will cause error when I use 'for in'  somewhere else

**Comment by mikebolt** [comment]
Yes, this is a serious issue:

    var x = {};
    > undefined
    x.__proto__
    > Object {getAll: function, removeAll: function, add: function, remove: function, update: function…}

I am working on a fix for this right now.

**Comment by mikebolt** [comment]
Fixed in 16.10.0.
