### ISSUE TITLE
Importing tween.js doesn't work

### ISSUE THREAD

**Issue by jramstedt** [tweenjs/tween.js#362]
import * as TWEEN from '@tweenjs/tween.js'
doesn't work anymore with version 16.10.0

**Comment by mikebolt** [comment]
I don't have a way of evaluating this right now, but I think I know the issue. Could you try putting 'var' at the beginning of [line 81](https://github.com/tweenjs/tween.js/blob/master/src/Tween.js#L81)?

    var TWEEN = new _Group();

I think if a variable leaks to the global scope then it will be part of the exported object, in addition to the module.exports value. Just a guess.

**Comment by siwel** [comment]
@jramstedt For what it's worth importing the _default_ export rather than the _named_ export works for me;

`import TWEEN from '@tweenjs/tween.js';`

**Comment by shelbeniskb** [comment]
In some project, missing 'var' will throw error: 

`Tween.js:81 Uncaught ReferenceError: TWEEN is not defined
    at Object.<anonymous> (Tween.js:81)`

**Comment by mikebolt** [comment]
Fixed in 16.11.0

**Comment by jramstedt** [comment]
Importing works now (17.1.0).

But calling TWEEN.update() gives
`TypeError: TWEEN.update is not a function`

I'm using webpack and babel.

**Comment by mikebolt** [comment]
Are you using 'require' or 'import'?

**Comment by jramstedt** [comment]
I'm still using import

**Comment by han0110** [comment]
@jramstedt you can try to console.log TWEEN.default, it has those functions.  It works like this:
```javascript
import * as TWEEN from '@tweenjs/tween.js';

animate = () => {
  ...
  requestAnimationFrame(this.animate);
  TWEEN.default.update();
  ...
}
```
I don't know why but it works!

**Comment by cod-e-ash** [comment]
@han0110 this method works for me as well, but not the right way i guess.. 
Anyone able to solve this?

**Comment by twastvedt** [comment]
> 
> 
> @jramstedt For what it's worth importing the _default_ export rather than the _named_ export works for me;
> 
> `import TWEEN from '@tweenjs/tween.js';`

^ This worked for me. I also needed to add a `default` to the Typescript definitions.
