### ISSUE TITLE
Most examples broken!

### ISSUE THREAD

**Issue by mikebolt** [tweenjs/tween.js#369]
I made a breaking change in v17.0.0 that changed the value of "this" inside of "onUpdate". Previously "this" referred to the target object, but now it refers to the tween.

The examples need to be updated to use the callback's single parameter instead of "this", for example:

    myTween.onUpdate(function(object) {
        domElement.style.left = object.x + 'px';
    }

**Comment by trusktr** [comment]
This is a nice API change.

It hink it'd be a good idea for examples to be fixed when we make breaking changes before releasing anew version.

**Comment by mikebolt** [comment]
I consider the examples part of the test suite and I usually check them before merging changes, but I must have forgotten.

**Comment by martikaljuve** [comment]
Linking PR #388.
