### ISSUE TITLE
code reviews.

### ISSUE THREAD

**Issue by trusktr** [tweenjs/tween.js#370]
Hello guys, I'd like to get more active in the project. :}

I turned on code reviews, that way we need someone to review changes (good for sanity checking, and making sure contributors are in agreement about direction, and generally good practice for collaboration).

I am ready to be available to do reviews. At first I'll be only doing reviews and providing ideas (and @mikebolt you'll probably be making all PRs 😄).

I really want to be involved, so I'm ready to review PRs.

**Comment by trusktr** [comment]
I still need to digest all the changes since Sole eased away from development.

@mikebolt Can you get me to speed on the major changes, if any (not necessarily bug fixes or code improvements, but more like feature changes and big refactorings if any)

**Comment by mikebolt** [comment]
Well, the examples are still broken, and that's important, but I'm very lazy.

I would like to test and merge #366. It will need new documentation.

**Comment by mikebolt** [comment]
Code reviews are good but I removed the rule that enforced code reviews for PRs so that I could close up some old issues and PRs.
