### ISSUE TITLE
extensibility

### ISSUE THREAD

**Issue by trusktr** [tweenjs/tween.js#371]
I find that in my projects I add features by extending the class. This can be a good way to prototype what features we' like to move into the Tween class. Also, it may not need to be specifically through extension, it could be through event hooks or something.

On that note, let's think about how we can make it easy to extend functionality of Tween. My first PR on moving methods to `prototype` was one such way to make it easier. Are there other ways?

(This is more of a discussion sort of issue, maybe we need a label for that).

**Comment by mikebolt** [comment]
One could extend TWEEN.Tween and automatically set the _onUpdated function. This could make it easy to reuse code, e.g. moving divs or setting properties on THREE.js objects. example: "FullTurnTween" could perform a 360 degree turn about an axis.
