### ISSUE TITLE
zenhub

### ISSUE THREAD

**Issue by trusktr** [tweenjs/tween.js#372]
I use ZenHub on my GitHub repos, it's really awesome what it adds to issue tracking. It's similar to GitHub's new "Projects" feature, but better (and ZenHub came out first).

Then we can track f.e. Backlog, ToDo, In Progress, Review/QA, Done, and add/remove more columns of the "kanban" style board.

Once ZenHub is installed for you, you can see it right now in the "Boards" tab that ZenHub adds to GitHub.

It looks like this right now:

![screenshot 2017-09-16 at 2 03 31 pm](https://user-images.githubusercontent.com/297678/30516005-e1c8a33c-9ae7-11e7-86c2-6201b775b285.png)

**Comment by dalisoft** [comment]
Very nice, not for projects-like managing as i'm rarely do this. But awesome switching repo, iframe-based issue/pr and etc. Makes workflow eaiser. Thank you
