### ISSUE TITLE
Removing the global TWEEN group.

### ISSUE THREAD

**Issue by trusktr** [tweenjs/tween.js#374]
Let's discourage bad practices (using globals). Let's not have TWEEN be a global group. If people want groups, they can make them manually with the Group class. TWEEN can serve only as a namespace for when using Tween.js globally via script tag. f.e., TWEEN would only contain `TWEEN.Group` and `TWEEN.Tween`, etc, but there would be no methods and and no stored Tween instances in TWEEN.

**Comment by trusktr** [comment]
This would be a breaking change. We could deprecate it, leave it working for a while but remove any mention of it from the docs, then eventually remove it.

**Comment by mikebolt** [comment]
I'm going to leave it as-is because it keeps the examples shorter, it's easier to use, and it seems to be sufficient for most use cases.

**Comment by mikebolt** [comment]
... and now that it's provided as an ES6 module there's an easy way to prevent accidentally sharing the default group with another script that uses tween.js.
