### ISSUE TITLE
Rotate to movement Vector?

### ISSUE THREAD

**Issue by Jertiri** [tweenjs/tween.js#380]
Hi is in tween.js  a way to turn(rotate) the mesh towards the target.

By the way i use OBJLoader of three.js but that should have no effect on the mesh rotation

Greets Richie

**Comment by mikebolt** [comment]
Yes, you may animate an object's rotation like this:

    new TWEEN.Tween(myObject.rotation).to({x: xAngle, y: yAngle, z: zAngle}, duration).start();

Depending on the start and end values this may look odd. If you want a direct rotation, where the object will rotate along the shortest "arc" from start to end, then there is some math involved.

**Comment by Jertiri** [comment]
hi back, now i found time again to work further on these project.

I just wanted to develop a mathematical correct formula. Since I have the function found

Best at these on tween start
`.onStart(function () {
YOURMESH.lookAt (v3target);
}`


For all who read this issue, this is a quick fix for these Problem unfortunately without a smooth rotation.
