### ISSUE TITLE
Animation stops after 3 events

### ISSUE THREAD

**Issue by Zahma** [tweenjs/tween.js#381]
I'm curretly developing a code that uses Canvas Flow Map and Tween for animation.
After 3 events on the map the flows dont show up any more, I explored the object Tween.tween and I found that for the first time the object contains the following: 

- [here](https://imgur.com/a/KwXLK)

after the fourth event the object looks like this:

- [here](https://imgur.com/a/S3Zcy)

so the valuesStart offset keeps increasing untill there is no animation.
How can I set the start value always to 0 ?
or is there any other alternative to overcome this issue ?

**Comment by mikebolt** [comment]
Can you set the value to 0 immediately before you start each tween, inside
your event handler?

**Comment by mikebolt** [comment]
Did you resolve this issue yet?
