### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by smatthews1999** [tweenjs/tween.js#383]
Are there any?  Thanks.

**Comment by mikebolt** [comment]
No, but it's not a bad idea.

**Comment by martikaljuve** [comment]
There are definitions at https://www.npmjs.com/package/@types/tween.js. Install them with:
`npm install --save-dev @types/tween.js`

It would be nice to have the definitions live inside this repository as well (as described in https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)

**Comment by subvertallchris** [comment]
Has anyone had trouble using these definitions? I get the following error:

```
File '/AbsolutePathToProject/node_modules/@types/tween.js/index.d.ts' is not a module
```

Using `@types/tween.js` and `tween.js` in my package.json.

**Comment by scambier** [comment]
@subvertallchris You should install `@tweenjs/tween.js`, not `tween.js`

Then you can `import * as TWEEN from '@tweenjs/tween.js'`

**Comment by dukuo** [comment]
Am I wrong or `@types/tween.js` are for another package with the same name? Has anyone tested this?

**Comment by scambier** [comment]
You have a look at the source at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/tween.js/index.d.ts

At the very bottom, it references @tween/tween.js
```
declare module "@tweenjs/tween.js" {
    export = TWEEN;
}
```

I'm using these 2 packages in a personal project, and it's working fine :)
```
import * as TWEEN from '@tweenjs/tween.js'

(...)

this.tweenFloat = new TWEEN.Tween({ y: this.y })
  .to({ y: this.y - 30 }, 900 + Math.random() * 200)
  .onUpdate((o: any) => {
    this.y = o.y
  })
  .easing(TWEEN.Easing.Quadratic.InOut)
  .repeat(Infinity)
  .yoyo(true)
  .start()
```

**Comment by dukuo** [comment]
Thanks @scambier, I mistakenly added `@types/tweenjs` without the dot, which was for CreateJS's TweenJS 😆

**Comment by julien-c** [comment]
Would be awesome to have the typings in the same repo as this one (like for Three.js)

**Comment by mikebolt** [comment]
Well, good news. I started learning TypeScript. I'll see what I can do.

**Comment by nidorx** [comment]
https://github.com/tweenjs/tween.js/pull/510

**Comment by trusktr** [comment]
Closing in favor of https://github.com/tweenjs/tween.js/pull/510.

**Comment by pahund** [comment]
For anyone who finds this when googling for “tween.js typescript” or something:

TypeScript type definitions are now included in the npm package *\@tweenjs/tween.js*. You do **not** have to install them separately. The npm package *\@types/tween.js* is **deprecated**.

**Comment by mhfaust** [comment]
When installing latest in a NextJS/TS app, I'm getting this error on import:
```
Could not find a declaration file for module '@tweenjs/tween.js'. '/Users/michaelhildebrand-faust/git/cube-solver/node_modules/@tweenjs/tween.js/dist/tween.esm.js' implicitly has an 'any' type.
  There are types at '/Users/michaelhildebrand-faust/git/cube-solver/node_modules/@tweenjs/tween.js/dist/tween.d.ts', but this result could not be resolved when respecting package.json "exports". The '@tweenjs/tween.js' library may need to update its package.json or typings.ts(7016)
```

**Comment by xiaohk** [comment]
> When installing latest in a NextJS/TS app, I'm getting this error on import:
> 
> ```
> Could not find a declaration file for module '@tweenjs/tween.js'. '[path-to-my]/node_modules/@tweenjs/tween.js/dist/tween.esm.js' implicitly has an 'any' type.
>   There are types at '[path-to-my]/node_modules/@tweenjs/tween.js/dist/tween.d.ts', but this result could not be resolved when respecting package.json "exports". The '@tweenjs/tween.js' library may need to update its package.json or typings.ts(7016)
> ```

I have the same issue here. Do you find any solution?

**Comment by trusktr** [comment]
Hey you all, I've been meaning to circle back to this. I am planning to improve the projet layout soon, and in the meantime #673 is going in.
