### ISSUE TITLE
NaN elapsed percentage when start time is equal to update time and duration is zero.

### ISSUE THREAD

**Issue by jharris4** [tweenjs/tween.js#384]
In the following code https://github.com/tweenjs/tween.js/blob/678cd11a909990b3ff007d458008843939626b37/src/Tween.js#L344

```
elapsed = (time - this._startTime) / this._duration;
elapsed = elapsed > 1 ? 1 : elapsed;
```

elapsed can end up as `NaN` when time === this._startTime and this._duration === 0.

This is explained here: https://stackoverflow.com/questions/18838301/in-javascript-why-does-zero-divided-by-zero-return-nan-but-any-other-divided-b

(TLDR; `1/0 === Infinity` and `1/0 > 1 === true`  vs `isNaN(0/0) === true` and `0/0 > 1 === false`)

The fix for this is to change the code to:

```
elapsed = this._duration === 0 ? 1 : (time - this._startTime) / this._duration;
elapsed = elapsed > 1 ? 1 : elapsed;
```

**Comment by mikebolt** [comment]
Would you like to make a PR for this? I can add the unit test.

**Comment by jharris4** [comment]
I'm traveling at a conference this week, and it'd take me a little time to clone the repo to make the PR.

If you're comfortable making the change yourself that'd be great. Otherwise I can try and get to it next week...

**Comment by mikebolt** [comment]
OK, I can do it.
