### ISSUE TITLE
group.getAll() not returning group tweens

### ISSUE THREAD

**Issue by lukechilds** [tweenjs/tween.js#389]
If I add tweens to the global instance with:

```js
new TWEEN.Tween({ foo: 0 });
new TWEEN.Tween({ bar: 0 });
```

I can get a reference to the them with:

```js
TWEEN.getAll();
// [tween, tween]
```

However if I try and be a good JavaScript citizen and use a group to encapsulate all of my tweens inside my app:

```js
const group = new TWEEN.Group();
new TWEEN.Tween({ foo: 0 }, group);
new TWEEN.Tween({ bar: 0 }, group);
```

I can't get a reference to the them:

```js
group.getAll();
// []
```

Is this a bug or am I doing something wrong?

**Comment by lukechilds** [comment]
Ahh, my bad, looks like tweens are only available in `.getAll()` while they're active. So after they've been called with `.start()` and before they've finished tweening.

I was expecting to be able to do something like:

```js
group
  .getAll()
  .forEach(tween => tween.start());
```

**Comment by lukechilds** [comment]
Assuming there's no built in way to do this then? I just have to keep my own reference of all my tweens to loop over and start them?

**Comment by mikebolt** [comment]
Yes, we do this to avoid memory leaks, but you can keep a reference to each
tween you create if it's useful for you.
