### ISSUE TITLE
Don't mutate object

### ISSUE THREAD

**Issue by lukechilds** [tweenjs/tween.js#390]
Hey, I'm using tween.js to animate a React project and it's great, good work!

The only issue is I'm tweening state values. By default tween.js mutates the original object which causes problems in React. Is it possible to use tween.js without mutating the original object.

e.g something like:

```js
const obj = { opacity: 0 };
new TWEEN.Tween(obj)
  	.to({ opacity: 1 }, 200)
    .onUpdate(val => {
      console.log(val);
      // { opacity: 0.1234 }
      console.log(obj);
      // { opacity: 0 }
    });
```

**Comment by mikebolt** [comment]
I was just working on something like this. I think you can accomplish this
by carefully extending the Tween class. I will try to share my code with
you soon.

**Comment by lukechilds** [comment]
Thanks, I'm building timeline functionality on top of tween.js for a project I'm working on. I have a solution but would be interested to see yours too.

This is my add tween method:

```js
tween(path, opts) {
    const obj = { value: objectPath.get(this.initalAnimationState, path) }
    const tween = new TWEEN.Tween(obj, this.group)
      .to({ value: opts.to }, opts.duration);
    tween.path = path;
    this.tweens.push(tween);
    return tween;
  }
```

And then I call this in `requestAnimationFrame`:

```js
getAnimationState(oldAnimationState) {
    this.group.update();
    const newAnimationState = immutable(oldAnimationState);
    this.tweens.forEach(tween => newAnimationState.set(tween.path, tween._object.value))
    return newAnimationState.value();
  }
```

If it works well I'll release it as open source 👍

**Comment by mikebolt** [comment]
OK. I was going to recommend passing a copy of your object to the tween
constructor using object.create.

**Comment by lukechilds** [comment]
Yeah, the issue is I need to rebuild an immutable version of the original object.

I'll close this issue now as I have a working solution, thanks for your help!

Is `tween._object` safe to use btw? It's not gonna be randomly removed/renamed in a future update?
