### ISSUE TITLE
excuse me,I can't get "object.x" in onUpdate callback

### ISSUE THREAD

**Issue by zhaoqize** [tweenjs/tween.js#402]
- tween.js version is 16.3.5

according to [user_guide](https://github.com/tweenjs/tween.js/blob/master/docs/user_guide.md#using-a-custom-easing-function),I try to use it。
```js
tween.onUpdate(function(object) {
	console.log(object.x);
});
```
But I can not get  value of `object.x`，it print `undefined` in console。
like this: https://codepen.io/zhaoqize/pen/baqgjq?editors=1111

Is not that what I wrote?

thanks!

**Comment by dalisoft** [comment]
Hi @zhaoqize 
I see some guides was not updated.
FYI, there main package path was updated from `tween.js` to `@tweenjs/tween.js`

Change tween.js in config from
`
https://cdnjs.cloudflare.com/ajax/libs/tween.js/16.3.5/Tween.min.js
`
to
`
https://unpkg.com/@tweenjs/tween.js
`

And your pen should work fine

**Comment by zhaoqize** [comment]
Wow, thank you very much！

The result is the same as I expected。

**Comment by wangkewei1993** [comment]
1.
npm install @tweenjs/tween.js
2.
import TWEEN from "@tweenjs/tween.js";
