### ISSUE TITLE
How can I stop .repeat(Infinity)

### ISSUE THREAD

**Issue by churkinv** [tweenjs/tween.js#411]
Hi, I  have the follwing code
`    for (var j = 10; j > 0; --j) {
           if (i == this.positions_1.length) i = 0;
           var tween = new TWEEN.Tween(this.reelOne[0].position)
                .to(this.positions_1[i], 1000)
                .repeat(Infinity)
                .start();
            i++;
        }`
Could advise what is the way to stop it? 
I tried:
`
   var tween = new TWEEN.Tween(this.reelOne[0].position)
                .to(this.positions_1[i], 1000)
                .repeat(Infinity)
                 .onUpdate(function(){if (i==10) tween.stop()})
                .start();` 
but it doesn`t seem to be working. Thanks

**Comment by trusktr** [comment]
Might be related to this one, not sure yet: https://github.com/tweenjs/tween.js/issues/406

**Comment by trusktr** [comment]
This is now fixed (and tested).
