### ISSUE TITLE
Doesn't work with ES6 imports

### ISSUE THREAD

**Issue by PierfrancescoSoffritti** [tweenjs/tween.js#412]
Would be nice to be able to import the module using ES6 syntax:
`import * as TWEEN from '@tweenjs/tween.js';`

**Comment by igeligel** [comment]
I also want to use this library with `import/export` syntax.

Is someone not ok with me creating a [rollup build](https://rollupjs.org/guide/en) for this library? Otherwise, I would start a pull request in this week?

**Comment by igeligel** [comment]
@PierfrancescoSoffritti See my pull request in the log.

If you want to use the build already now lookup my repository: [igeligel/tween.js](https://github.com/igeligel/tween.js/tree/rollup-build) on rollup-build branch

or download it from [npm](https://www.npmjs.com/package/tween-js-modern-module).

**Comment by colinsullivan** [comment]
This works for me with babel:

```
npm install @tweenjs/tween.js
```

```
import TWEEN from '@tweenjs/tween.js'
```

**Comment by mikebolt** [comment]
This is an ES5 library so I'm not going to add an export statement. Try what colinsullivan suggested or add something like this to the end of Tween.js:

    export default TWEEN;

**Comment by mudroljub** [comment]
You can't stay ES5 forever...
