### ISSUE TITLE
Readme/docs are missing info about proper Tween removal

### ISSUE THREAD

**Issue by Scharnvirk** [tweenjs/tween.js#416]
Hi, 

If I am understanding things correct, to fully remove Tween instance from memory (by freeing all references to it), one has to call following method:

`TWEEN.remove(yourTweenObject)`

This does not seem to be specified. 

Example of the way I am using tweens:

```
 const tween = new TWEEN.Tween()
        tween.to({x: config.targetScaleX, y: config.targetScaleY}, config.durationMS / 2)
            .easing(config.easeFn)
            .start()
            .onComplete(() => this.onTweenComplete)
        return tween

// and later 
private onTweenComplete() {
        TWEEN.remove(this.tween)
        this.tween = null
        //some further unrelated code
    }
```

Maybe it is me doing something wrong, but I think it is just a piece of missing info. It is very easy to miss this memory leak as tween objects are tiny, and you really need A LOT of them to make a noticeable dent in your memory.

**Comment by mikebolt** [comment]
Nevermind, the library does remove completed tweens from memory as long as the second argument to TWEEN.update is not truthy. Otherwise there will only be a memory leak if you create many tweens that never finish, or if you keep your own references to many tweens.

Did you find a memory leak?
