### ISSUE TITLE
delay is multiplied by ten when start() is given a ms value as a string

### ISSUE THREAD

**Issue by EmNudge** [tweenjs/tween.js#417]
It isn't written in the docs that start() even can get passed a value instead of using delay(), but it can. What's weird is that, when passed a string instead of a number, the number is parsed and then multiplied by ten.
**start(5000)** gives it a 5 second delay, while **start('5000')** gives it a 50 second delay.

If I had to guess what the problem is, I'd say it's probably by
`		this._startTime = time !== undefined ? typeof time === 'string' ? TWEEN.now() + parseFloat(time) : time : TWEEN.now();
		this._startTime += this._delayTime;`
and when it's adding the delayTime, it's concatenating them (i.e. parseFloat() didn't work and this._startTime is registering as a string. Thus it added a 0 to itself and only works as a number later on).

fix? I guess something like `this._startTime = parseFloat(this._startTime) + this._delayTime` but I'm not really sure why the issue appears in the first place.

**Comment by trusktr** [comment]
I fixed the relative_start_time example today. We should have been more careful when merging things, to keep other things up to date.
