### ISSUE TITLE
why _valuesStartRepeat[property] is added by _valuesEnd[property] when the type of _valuesEnd[property] is string?

### ISSUE THREAD

**Issue by nfyfamr** [tweenjs/tween.js#418]
I wrote some easy code using tween.

    const origin = [ 0, 0, 0 ];
    const target = [ '1', '0', '0' ];
    const t = new TWEEN.Tween( origin )
            .to( target )
            .repeat( Infinity )
            .onUpdate( obj => console.log(obj) )
            .start();

I wished the obj value will be changed in range between [0,0,0] and [1,0,0] repeatedly, but the result was not that way. the result look like starting point is moving at each repetition.
After some inspection I found that when _valuesEnd[property] is sting, _valuesStartRepeat[property] is added by it.
Why this codes inserted? If there is no reason, I think this should be edited.

the link of problem line is following: https://github.com/tweenjs/tween.js/blob/f58e2f0e6f979ac8261952b1292501a7fed6afcf/src/Tween.js#L404

**Comment by mikebolt** [comment]
It's just assuming that string values are relative values, e.g. '+4'. Look at this section: https://github.com/tweenjs/tween.js/blob/f58e2f0e6f979ac8261952b1292501a7fed6afcf/src/Tween.js#L370

The code near line 404 should do the same thing. Want to make a PR?

**Comment by nfyfamr** [comment]
ok i understand. thanks
