### ISSUE TITLE
Tween.js rotation is broken in Three.js

### ISSUE THREAD

**Issue by brandonballard** [tweenjs/tween.js#419]
I've been using tween.js for smooth rotation of aThree.js Object3D, it has suddenly stopped working, others such as smooth scaling or smooth movement work, but not rotation.

Ex: new TWEEN.Tween(Configurator.rootObj.rotation).to({ y: (Configurator.rootObj.rotation.y + 1.5)},700).delay(400).easing(TWEEN.Easing.Quadratic.Out).start();

**Comment by mikebolt** [comment]
What is the issue? Does it not animate, does it go the wrong direction, or is it not smooth?

Also, try this and let me know if it works as expected:

    var yRotationTween = new TWEEN.Tween({y: Configurator.rootObj.rotation.y}).to({ y: (Configurator.rootObj.rotation.y + 1.5)},700).delay(400).easing(TWEEN.Easing.Quadratic.Out);
    yRotationTween.onUpdate(function(object) {
        Configurator.rootObj.rotation.y = object.y;
    });
    yRotationTween.start();

**Comment by brandonballard** [comment]
The issue is nothing happens, there is no animation. If I use the same code but animate the scale instead of the rotation, it works fine. 

I tried your code and the object vanished from sight.  After I ran the code I got the result: Configurator.rootObj.rotation.y = undefined

**Comment by martikaljuve** [comment]
Both ways seem to work fine: http://jsbin.com/comehunero/edit?html,output

**Comment by mikebolt** [comment]
@brandonballard I think your error was caused because older versions of Tween.js passed in the tween as the parameter to the callbacks instead of the tweened objects, as it does now in version 17. I'm closing this because I don't think it's an issue with Tween.js.

**Comment by christophknoth** [comment]
@mikebolt If you could update the README.md with the new version that would have saved me some hours today ;)
