### ISSUE TITLE
tween.js rotation such likes setlocalPotion way.

### ISSUE THREAD

**Issue by gkgkska** [tweenjs/tween.js#420]
Hello, I need help.

Is it anyway I can input tween-rotation value such like to set up local position value?

Here is my code.
var obj = document.getElementById('box');

obj.prototype.reset = function(){
if(this.tween){
   this.tween.stop();
}

this.entity.setLocalposition(x, y, z);

this.tween = this.entity.tween(this.entity.getLocalPosition())
      .to(new pc.Vec3(0, 0.5, -0.1), this.duration, pc[this.easing]);
      this.tween.start();
}

// positioning set local position perfectly works. 
// I've been believing that it anyway I can do it same as this function process like 

var obj = document.getElementById('box');

obj.prototype.reset = function(){
if(this.tween){
   this.tween.stop();
}

this.entity.setLocalRotation(x, y, z);

this.tween = this.entity.tween(this.entity.getLocalPosition())
      .to(new pc.Vec3(0, 0.5, -0.1), this.duration, pc[this.easing]);
      this.tween.start();
}

Thanks,

**Comment by mikebolt** [comment]
So you want to both move and rotate an object with a tween when `reset` is called? In your second code example you call setLocalRotation, but you create a tween for the position.

Could you please tell me what library the `pc` variable is from?

**Comment by mikebolt** [comment]
I'm closing this issue because I don't know how to help.
