### ISSUE TITLE
`performance.now` as default TWEEN.now() in Node.js?

### ISSUE THREAD

**Issue by colinsullivan** [tweenjs/tween.js#422]
I am using tween.js to run LED animations on a raspberry pi, and thus am sensitive to performance issues.  It is a musical project, and thus I am also sensitive to tight timing issues.

Once I did the following, everything started working much more smoothly:

* use `setImmediate` to substitute for `requestAnimationFrame`
* pass `performance.now()` into `TWEEN.update()`
* pass `performance.now()` into `<tween instance>.start()`

I don't have a comprehensive test for you at this time - though perhaps TWEEN.now() should be `performance.now` if it is available in Node?

**Comment by mikebolt** [comment]
performance.now() is not available in Node.js. I added support for Node.js by using process.hrtime instead. It should be very accurate. Does your project run in Node.js or in a browser?

**Comment by colinsullivan** [comment]
There is a `performance.now` API in node, and you are right, the default TWEEN.now is very accurate.

https://nodejs.org/api/perf_hooks.html

For me this was a red herring, memory allocations in my TWEEN instances were causing animations to behave inconsistently.
