### ISSUE TITLE
Queue system needed for rapidly initiated successive tweens with onComplete handlers that have side effects

### ISSUE THREAD

**Issue by rtpHarry** [tweenjs/tween.js#428]
I have wired up a transition tween to swap between the display of two models in Three.js.

I have used the `onComplete` handler to update the system after the animation has completed.

This has unavoidable side effects (for example setting `previousObject.visible=false` after it has been transitioned out, and updating my new current object).

The problem that occurs is that if I toggle the radio buttons quickly then the tweens get fired off quickly and it ends up with multiple tweens running at the same time, interleaving the `onComplete` handlers and distorting the state of my app.

The global infrastructure is already there, so what I need is some kind of queue system that will push the tween into a named queue and start one when the other ends.

The current methods don't provide enough functionality to achieve this out of the box.

For more context, I have a (StackOverflow question open)[https://stackoverflow.com/questions/52481051/add-tweens-to-be-completed-sequentially-when-triggered-from-rapid-ui-events].

I know there is chaining but that assumes you can set it up beforehand. In this case, the number of animations depends on the ongoing interactions in the ui layer. 

Am I correct that this is a missing feature or have I misunderstood the docs?

**Comment by mikebolt** [comment]
I think you could do this with an onComplete callback that holds a tween
queue in closure. This could be done generically and included in tween.js
for convenience.

**Comment by rtpHarry** [comment]
I had an attempt at doing this but I don't think I know JavaScript well enough yet to get this right.

This is what I wrote:

```
import TWEEN from '@tweenjs/tween.js';

export default class TweenQueue {
    constructor() {
        // Tween queue
        this.tweenQueue = [];
    }

    addTweenToQueue(tween, rndHex) {
        let existingCallback = tween._onCompleteCallback;

        tween.onComplete( () => {
            console.log("%c oncomplete tweenqueue item", 'background-color: ' + rndHex + ';', rndHex);

            if(existingCallback) {
                console.log("callback existed, calling now");
                existingCallback();
            }

            if(this.tweenQueue.length) {
                console.log("removing top tween");
                this.tweenQueue.shift();
            }

            if(this.tweenQueue.length) {
                console.log("starting top tween");
                this.tweenQueue[0].start();
            }
        });

        let startQueue = (this.tweenQueue.length ? false : true);

        this.tweenQueue.push(tween);

        if(startQueue) {
            console.log("empty queue, starting");
            this.tweenQueue[0].start();
        }
    }
}
```

And I wrapped two tweens up inside their own tween queue but it still got tangled.

**Comment by mikebolt** [comment]
That looks right assuming you're using it correctly.

My suggestion is to see if multiple tweens are updating simultaneously. Please download Tween.js and manually include it in your project. Then edit it like this, near line 330:

    update: function update(time) {

        console.log('updating tween ' + this._id); // add this line

        var property;
        var elapsed;
        var value;
        // ...

Or you could add a breakpoint on line 332.

**Comment by mikebolt** [comment]
won't fix
