### ISSUE TITLE
Recalculating end values on start

### ISSUE THREAD

**Issue by lguminski** [tweenjs/tween.js#429]
I am starting a tween with a delay, and I need to calculate the `to()` parameters in the moment it actually starts. So I expected that `onStart` handler would give me the chance. At least this is what documentations says
> **onStart**
> Executed right before the tween starts--i.e. before the deltas are calculated. 

In reality the `onStart` handler is called on the first execution of the `update()` function, which is *after* all deltas had been already calculated.
https://github.com/tweenjs/tween.js/blob/cf132ffd72a608037258a7cc746dbd36abdebb4e/src/Tween.js#L321

This does not agree with what documentation says.

EDIT: I think I was wrong. Deltas are calculated indeed later. But the `to()` values are taken already earlier in `start()`, so that's why my scenario doesn't work. If `onStart` would be called really *on start*, then it would work.

**Comment by lguminski** [comment]
I found a hackish workaround.

So like I said I needed to calculate `to()` values when the tween is actually starting. My case was additionally complicated by the fact that I need to tween to array of values. For it to work, it is important to note that:

1. even though you want to calculate end values in `onStart` handler, you need to provide fake array as an argument to `to()` function. And the array cannot be empty.
1. `tween.js` does not treat `to()` arguments as immutable. If you provide an array of values as an argument of `to()` function, then this library modifies it by adding the initial value at the beginning. If you want to calculate end values in the `onStart` handler, you need to repeat the operation yourself
https://github.com/tweenjs/tween.js/blob/cf132ffd72a608037258a7cc746dbd36abdebb4e/src/Tween.js#L173

Here is a working example:

    const toVector = {a: ["a non-empty array"]}; // fake argument
    const initialVector = {a: 0};
    const tween = new TWEEN.Tween(initialVector).to(toVector, 1000)
      .onStart(arg => {
        toVector.a = [initialVector.a, 10, 20];
        // note that the array has been prepended with initialVector.a
      })
      .onUpdate(pos => {
        console.log(pos);
      })
      .start();

It might easily break with future upgrades, but for now it is working.

I hope it helps someone with the same problem. The issue can be closed.

**Comment by lguminski** [comment]
this can be even simpler
    
    const toVector = {a: ["a non-empty array"]}; // fake end values
    const initialVector = {a: "whatever"}; // fake initial value

    const tween = new TWEEN.Tween(initialVector).to(toVector, 1000)
      .onStart(arg => {
        toVector.a = [0, 10, 20];
      })
      .onUpdate(pos => {
        console.log(pos);
      })
      .start();

**Comment by mikebolt** [comment]
Sorry this was so difficult. I didn't anticipate this use case.

As a solution, I would have implemented the delay myself, then created the tween at the appropriate time with the appropriate values, then immediately called its `start` method.

I just updated the user guide to explain when onStart is called.
