### ISSUE TITLE
[QUESTION] Managing Groups of Tweens

### ISSUE THREAD

**Issue by joeredfearn** [tweenjs/tween.js#430]
Hello there, I have a question regarding the management of many many groups of tweens. Let me try and describe my situation. The game I am working on has many scenes each with its own TWEEN.Group allowing the the scene to only update the tweens that should be currently active. A scene can obviously own multiple objects, each potentially with its own TWEEN.Group forming a basic hierarchy. 

The idea being that when lets say the SplashScene is not being updated (for example it is not in focus) then all its tweens cease updating, including the tweens of the objects that the SplashScene tells to update. This reduces the amount individual management needed for things like, pausing the game for example. Instead of manually pausing each group, or tween, we simply just don't update the scene.

TweenJS has everything in place to support this concept apart from one issue. The dependency on TWEEN.now() which returns Date.now(). This means that upon resuming the update of my scene all the tweens and child tweens jump to where they should be, rather than simply continuing to update.

I have tried to patch this myself by assigning every TWEEN.Group its own 'time' variable that is incremented by its .update function and then passed to tweens added. But although very close it seems to run slightly faster than normal which is actually affecting gameplay. A second delay takes about 970ms.

What am I doing wrong?

I'm sure I have just missed something basic and someone else has tried this same idea? Other than this I have nothing but praise for TweenJS, it is a fantastic library.

**Comment by mikebolt** [comment]
It sounds like you have the right idea. I probably can’t be of help to you
without looking at the code. 970ms is about one frame less than one second
at 60fps. I would check if update is called before or after the internal
time is increased, and whether the updates are always accompanied by a time
increase. It is also possible that you are timing it incorrectly. Also,
don’t assume that requestAnimationFrame is exactly 60fps, and calculate the
time deltas manually.

**Comment by joeredfearn** [comment]
ok thanks mate - some good points there, will take a look!

Any other opinions are still welcomed.

**Comment by joeredfearn** [comment]
ok so I figured I would post the code. Let me know @mikebolt if there is anything wrong with my implementation?

I appreciate your help!

```javascript
TWEEN.Group.prototype.time = 0;
    TWEEN.Group.prototype.update = function(time, preserve) {
        var tweenIds = Object.keys(this._tweens);
        if (tweenIds.length === 0) {
            return false;
        }
        time = time !== undefined ? time : this.time;
        while (tweenIds.length > 0) {
            this._tweensAddedDuringUpdate = {};

            for (var i = 0; i < tweenIds.length; i++) {
                var tween = this._tweens[tweenIds[i]];
                if (tween && tween.update(time) === false) {
                    tween._isPlaying = false;
                    if (!preserve) {
                        delete this._tweens[tweenIds[i]];
                    }
                }
            }
            tweenIds = Object.keys(this._tweensAddedDuringUpdate);
        }
        this.time += window.dt;
        return true;
    };

    TWEEN.Tween.prototype.start = function(time) {
        this._group.add(this);

        this._isPlaying = true;

        this._onStartCallbackFired = false;

        this._startTime = time !== undefined ? typeof time === 'string' ? this._group.time + parseFloat(time) : time : this._group.time;
        this._startTime += this._delayTime;

        for (var property in this._valuesEnd) {
            if (this._valuesEnd[property] instanceof Array) {
                if (this._valuesEnd[property].length === 0) {
                    continue;
                }
                this._valuesEnd[property] = [this._object[property]].concat(this._valuesEnd[property]);

            }
            if (this._object[property] === undefined) {
                continue;
            }

            this._valuesStart[property] = this._object[property];

            if ((this._valuesStart[property] instanceof Array) === false) {
                this._valuesStart[property] *= 1.0;
            }
            this._valuesStartRepeat[property] = this._valuesStart[property] || 0;
        }

        return this;
    };
```

**Comment by alexburner** [comment]
@joeredfearn this seems like a useful addition to TWEEN.Group, could you open a PR with your work?

**Comment by joeredfearn** [comment]
I would be more than happy to but its not quite 100% yet. I still have the issues where the timing is slightly sped up. Any help would be greatly appreciated!

**Comment by johnmarinelli** [comment]
Hi, is this in the library yet?  I get `Uncaught TypeError: TWEEN.Group is not a constructor` when using the CDN version of tween.js.

**Comment by mikebolt** [comment]
Please try getting the package from npm or the master branch on github. I
will figure out why the cdn isn’t updating.

**Comment by mikebolt** [comment]
`pause` and `resume` now accept timestamps. This should fix the issue.
