### ISSUE TITLE
when run onCompleteCallback, create new tween, will error

### ISSUE THREAD

**Issue by stanleySHU** [tweenjs/tween.js#434]
when run onCompleteCallback, create new tween, will error.  because oncomplete before remove tween when run update()

**Comment by mikebolt** [comment]
I just tested this and it did not cause an error. Check out this codepen: https://codepen.io/anon/pen/qLJVQg

I remember fixing this bug before. Please try using version 17.2.0. I'm going to close this issue, but if you still get an error with the new version then leave a comment. Thanks.

**Comment by stanleySHU** [comment]
if _tween array is [1,2,3,4], if i addition in complete stop a tween, maybe become [2,3,4], then addition a tween, become [2,3,4,5].  then return false, if index = 3, will remove 5. become [2,3,4]

**Comment by mikebolt** [comment]
Here's the commit that fixed the issue: https://github.com/tweenjs/tween.js/commit/8f5530ab1991c464d676bdb42a436c50d93c219a

_tweens was an array in the old version. It is an object now.
