### ISSUE TITLE
Integrating TweenJS with AngularJS 1.4 and ArcGIS JS API for vehicle graphic smooth Movement every 15 sec   

### ISSUE THREAD

**Issue by kAliRM70** [tweenjs/tween.js#444]
I have an Angular application which intergates ARCGIS Javascript API Map. I have a dispatcher with a MAP where we can have vehicles move around on the streets. Now my vehicles icons jumps as the GPS location updates. I need to smoothly move the vehicle from the current location to the newly updated location.

I tried to have the requestAnimationFrame inside the dispatcher controller and when ever a GPS update received a new instance of the Tween is created and passed to it new and old locations but it is not working  

Code Snippets are below

      // let fps, fpsInterval, startTime , then;
    // let startAnimating = (fps) => {
    //   fpsInterval = 1000/fps;
    //   then = Date.now();
    //   startTime = then;
    //   console.log(startTime);
    //   animate();
    // }
    //
    // startAnimating(20);

    // function animate(time) {
    //   requestAnimationFrame(animate);
    //   TWEEN.update(time);
    //   console.log("Animate");
    // }
    // requestAnimationFrame(animate);

// if(result){
            //   vehicle.graphic.attributes.currentPosition_X = result.location.feature.geometry.coordinates[0];
            //   vehicle.graphic.attributes.currentPosition_Y = result.location.feature.geometry.coordinates[1];
            // }
            //
            // let position = {
            //   x: vehicle.graphic.geometry.getLongitude(),
            //   y: vehicle.graphic.geometry.getLatitude(),
            //   heading: 180
            // };
            // console.log("position::", position);
            // let feature = {
            //   geometry: {
            //     coordinates: [0, 0],
            //     type: "Point"
            //   }
            // };
            // let target = {
            //   x: position.x + 0.0000000000009,
            //   y: position.y,
            //   heading: 180
            // };
            //  const geometryPromise2 = createGeojsonGeometry(feature);
            //  geometryPromise2.then(geom2 => {
            //   console.log("geom2::", geom2);
            //   vehicle.tween = new TWEEN.Tween(position).to({x: 0, y: 0}, 15000000000000000000000000000000).easing(TWEEN.Easing.Quadratic.InOut).onUpdate(() => {
            //     //vehicle.graphic.setGeometry(geom);
            //   }).start();
            // })

**Comment by mikebolt** [comment]
I don't think the problem is caused by Tween.js.
