### ISSUE TITLE
Provide an ES6 build of tween.js

### ISSUE THREAD

**Issue by Mugen87** [tweenjs/tween.js#459]
We are using `tween.js` in several `three.js` demos e.g. [css3d_periodictable](https://threejs.org/examples/css3d_periodictable). The example code is currently migrated to ES6 modules and it would be great if also external libraries like `tween.js` can be included via ES6 imports. So something like:
```js
import TWEEN from `./path/to/our/tween.module.js`;
```

**Comment by mikebolt** [comment]
Hi Michael. You can import tween.js after adding this line to the end of
Tween.js:

export {TWEEN};

I plan to add a script that will do this for you and place the result in
tween.es6.js. I also plan to have this done automatically by the CI.

**Comment by Mugen87** [comment]
> I plan to add a script that will do this for you and place the result in
tween.es6.js. I also plan to have this done automatically by the CI.

Sounds good! Definitely better than doing a manual modification.

**Comment by dirk-ecker** [comment]
This actually works:

`import TWEEN from '@tweenjs/tween.js'`

**Comment by mikebolt** [comment]
To use tween.js as an ES6 module follow these steps:

1. `npm i @tweenjs/tween.js`
2. `npm run build`
3. Copy `dist/tween.esm.js` somewhere
4. Use an import statement such as `import TWEEN from './js/tween.esm.js';`
