### ISSUE TITLE
NPM versions versus GIT tag versions?

### ISSUE THREAD

**Issue by aSqrd-eSqrd** [tweenjs/tween.js#460]
It seems something crazy happened with the NPM versions and the a bunch of GIT commits back in May 2019.

Could you clarify which NPM version and GIT tag version go together and which NPM version is the latest? NPM says, "v17.4.0", but here (GitHub) it looks like the tag v17.3.4 is the latest ?by time?, but there are three tags (v16.8.1 and two named v17.3.4) all tied to f67f085.

I'm confused and would appreciate any clarification that you could provide.

**Comment by mikebolt** [comment]
I was working on some issues with semantic release and the Travis CI config
and it caused some chaos with the git tags. 17.4.0 is the latest version.
