### ISSUE TITLE
Every tween.onComplete are executed 2 times

### ISSUE THREAD

**Issue by grevius5** [tweenjs/tween.js#461]
I have implemented twee.js with Pixi.js but i have this issue, for every tween with  onComplete function, that callback is called 2 times. An example:
new TWEEN.Tween(logo)
            .to({ alpha : 1 }, 1000)
            .easing(TWEEN.Easing.Quadratic.Out)
            .onComplete(() => {
                console.log("complete");
            })
            .start();
This code gives to me 2 "complete" in console.

**Comment by mikebolt** [comment]
One of the unit tests covers this. Please download the package and open
test/unit/nodeunit.html in your browser, and see if any tests fail.

**Comment by grevius5** [comment]
I have this result:
Tests completed in 311 milliseconds.
225 assertions of 225 passed, 0 failed.

**Comment by mikebolt** [comment]
Okay. Try these things:

1. Make sure that you only have one requestAnimationFrame loop.

2. Make sure that within your requestAnimationFrame loop TWEEN.update() is only called once.

3. Make sure that you are only logging "complete" in once place in your code. Perhaps make the log message more specific, like "onComplete callback for logo tween called".

4. If you're not using requestAnimationFrame, then make sure that the function that calls TWEEN.update() never calls it twice with the same timestamp.

If this doesn't help then please try to make an example app that demonstrates this issue.

**Comment by grevius5** [comment]
Sorry, it was my fault in code. That was not a bug.
