### ISSUE TITLE
Community Survey

### ISSUE THREAD

**Issue by mikebolt** [tweenjs/tween.js#464]
Please take a look at this survey and send a response if you wish. I'm open to any feedback about the survey itself. I would like to add this to the main README soon to get more responses.

https://docs.google.com/forms/d/e/1FAIpQLScJ0xnsS1m4mdXGRmGFPVd_CYi0Ah224lLYc4UP-fmakQjNHw/viewform?usp=sf_link

**Comment by chepe263** [comment]
I need permission to use the survey.

**Comment by mikebolt** [comment]
OK thanks for letting me know. I will make a new one with public access soon.

**Comment by mikebolt** [comment]
It's public now and the link is in the README.
