### ISSUE TITLE
17.5.0 entry point invalid

### ISSUE THREAD

**Issue by GenericMale** [tweenjs/tween.js#474]
In version 17.5.0 the package.json is already referring to the changed entry point (dist/tween.cjs.js)
but the entire dist folder is missing in npm.
I guess 17.x should still use the old entry point.
This is very critical for us because we are including a library which unfortunately doesn't pin down the tween.js version dependency (^17.1.0 is used) so this breaks all our previous releases.

**Comment by mikebolt** [comment]
Sorry!

I just unpublished version 17.5.0 on npm. You might need to remove node_modules and reinstall the affected project.
