### ISSUE TITLE
Possibility to FastForward and Rewind

### ISSUE THREAD

**Issue by dadostar** [tweenjs/tween.js#48]
I have two questions cause i'm new to javascript and tween.js

1) is there the possibility of fastforward and rewind the animation?

2) how can i stop completely the animation, in order to start again it from the beginning when i play it again?(i'm  using threejs)

Greets
David

**Comment by moscartong** [comment]
For fast forward the tween to the end, I do this:
```javascript
tween.update(Infinity);
tween.stop();
```
