### ISSUE TITLE
How to control FPS of onUpdate function?

### ISSUE THREAD

**Issue by ProgrammingLife** [tweenjs/tween.js#496]
Which FPS does use onUpdate function? How do I control it? For example if I want to fix it for 30fps, 60fps or even 120fps, 240fps for high quality monitors.

**Comment by mikebolt** [comment]
The update rate of requestAnimationFrame is controlled by the browser so
there is no way for us to increase the update rate. It is probably 60fps,
but it *might* be 90fps if WebVR  or WebXR is enabled.

You can artificially lower the fps by ignoring calls to your RAF callback.
I.e. for 30fps ignore every other call.
