### ISSUE TITLE
Request: provide version number

### ISSUE THREAD

**Issue by ldenevi** [tweenjs/tween.js#497]
Hi! This library is an integral part of my company's application and we allow 3rd party developers to use our app's TweenJS library. However, given the complexities of integrations it would be extremely helpful to have access to TweenJS' version at runtime.

All other libraries (JQuery, etc.) have a method that returns the version, which enables us to adapt to system changes at runtime. It will help us greatly if TweenJS also provided this.

**Comment by mikebolt** [comment]
I'm working on some node.js scripts to automate this. I have a working solution that uses bash and standard unix utils, which I could submit in the meantime.

**Comment by mikebolt** [comment]
Done, with the caveat that the manual builds must be done in the same commit as the version bump until I move to a better CI. The version is now available as `TWEEN.version`.

What program are you working on?

**Comment by xamino** [comment]
https://www.navvis.com/indoorviewer

Thanks!
