### ISSUE TITLE
Use buildkite for build automation and CI

### ISSUE THREAD

**Issue by mikebolt** [tweenjs/tween.js#506]
I want to have a working build automation server for this project, but Travis-CI doesn't support that very well.

I want the server to build every commit that hits master (except its own) and then push a commit with the contents of the dist/ directory.

I don't want to submit a PR for version bumps. Ideally the person who approves the PR would be required to choose between major, minor, and patch, and everything would be automatic from there. If the CI has something like the semantic-release plugin that we used to use, then that would work too.

buildkite is a build and CI server with GitHub integration.

**Comment by trusktr** [comment]
We've since moved to GitHub Actions. So easy!
