### ISSUE TITLE
"const" should not appear in dist file

### ISSUE THREAD

**Issue by zhnoah** [tweenjs/tween.js#508]
1.This is not a uniform grammar.
2.This will cause some compression errors.

**Comment by Thefurypig** [comment]
I meet this problem too , and I use version 18.3.1 to resolve it

**Comment by mikebolt** [comment]
This is a bug. Rollup produces es6 code.

Quick fix: change const to var in the dist file.

Real fix: transpile es6 to es5 with babel.

**Comment by mikebolt** [comment]
Fixed with #509

We don't need to use babel.
