### ISSUE TITLE
env: typescript

### ISSUE THREAD

**Issue by unsuited** [tweenjs/tween.js#513]
hi~ 
```
new TWEEN.Tween({})
ts hint : 类型“_Group”上不存在属性“Tween"
```
Version：
typescript: 3.4.5
@tweenjs/tween.js: 18.5.0

Sorry to interrupt

**Comment by mikebolt** [comment]
Hi. Can you please describe the issue?

**Comment by unsuited** [comment]
Thank you for replying.
 It's like this:
![image](https://user-images.githubusercontent.com/24388564/78417400-2bb04180-7664-11ea-9c8a-adcf30289b34.png)

 The code can work properly.  It's just that typescript has a hint like this

**Comment by trusktr** [comment]
I have a plan for TypeScript, which should fix any discrepancies. I'll make a PR soon...

**Comment by trusktr** [comment]
TypeScript support has been merged in #544. Can you give it a try now?

A new version isn't published to NPM yet. We still need to do a few things, mainly #545 needs to be fixed first. Plus we should let the recent changes should sit around for a little bit, to make sure nothing is messed.

@mikebolt We should make a pre-release for 18.6.0; I'd be happy to help with that.

To try it out right now @unsuited, you can install from git. Place this in your `package.json`:

```json
{
  "dependencies: {
    "@tweenjs/tween.js": "tweenjs/tween.js#1f85d6e"
  }
}
```

then run `npm install` again. That's the commit that merged TypeScript changes.

**Comment by unsuited** [comment]
👍 👍 👍

**Comment by mikebolt** [comment]
Joe, are you able to publish to npm?

**Comment by trusktr** [comment]
Hello Mike! Not yet, but Sole got in contact by email, so I should be set soon.

**Comment by trusktr** [comment]
closed in https://github.com/tweenjs/tween.js/pull/544

@unsuited This isn't released yet, but you can add this to your `dependencies` in package.json to test it out:

```js
{
  "dependencies": {
    "@tweenjs/tween.js": "tweenjs/tween.js#6670ea6"
  }
}
```

We will release after the regression in https://github.com/tweenjs/tween.js/issues/545 is fixed.
