### ISSUE TITLE
Await finish of tween animation?

### ISSUE THREAD

**Issue by mtwzim** [tweenjs/tween.js#518]
Hi, I've recently been trying to make the for (loop) wait for an animation of the tween to end, but I can't in any way, is that possible? I really need to wait for the tween animation to finish before continuing the loop

![Screenshot_15](https://user-images.githubusercontent.com/42474938/80929878-e035a400-8d85-11ea-90ee-80109c86db99.png)

**Comment by trusktr** [comment]
Hello! Use `.onUpdate`, `.onComplete`, `.onStart`, or `.onStop`. There's no generic `.on` event handler method, only the specific ones. Hope that helps. Closing, but feel free to discuss if it doesn't work.

**Comment by christopherjbaker** [comment]
I had a similar need. I built a custom `TweenPromise` that extends `Promise`, but he underlying code is:
```js
new Promise((resolve) => {
  tween.onComplete(resolve)
  tween.onStop(resolve)
})
```

For those of you who want the full TweenPromise, here it is. This may or may not work depending on your build and deploy environments. Use as `await new TweenPromise(tween)` to just await completion. If you capture that promise, you can access the tween itself at `promise.tween` for any other operations. Most of my tween factories return this promise, as its a very common pattern for me when sequencing animations. It is better to use `.delay()` for animation sequencing, but this is a lot simpler.

```js
class TweenPromise extends Promise {
  constructor(tween) {
    super((resolve) => {
      tween.onComplete(resolve)
      tween.onStop(resolve)

      tween.start()
    })

    this.tween = tween
  }
}
```

**Comment by trusktr** [comment]
Neat. Thanks @christopherjbaker!
