### ISSUE TITLE
Option for Tween instances to remember last values

### ISSUE THREAD

**Issue by trusktr** [tweenjs/tween.js#522]
API improvement idea, with backwards compatibility:

```
new TWEEN.Tween(objectWithInitialValues, group, {rememberLastValues: true})
```

where `rememberLastValues` would make it so any time you call `start()` it will start with the last value where it previously was.

This will greatly improve the dev experience (f.e. it will make end user code much cleaner because instead of having multiple Tween instances we can have just one).

Here are two code examples, one before this change, and one after this change, showing that user code will be shorter once we add this feature (adapted from an actual project):

<details><summary>before this, 51 lines of code needed:</summary>

```js
class ExampleBeforeAPIChanges {
	openTween = null
	closeTween = null
	menuOpen = false
	tweenRAF = null

	makeOpenTween() {
		this.openTween = new TWEEN.Tween({menuPosition: (someObject && someObject.position.x) || 0})
			.onComplete(() => this.openTween.stop())
			.onUpdate(obj => (someObject.position.x = obj.menuPosition))
			.easing(TWEEN.Easing.Exponential.Out)
	}

	makeCloseTween() {
		this.closeTween = new TWEEN.Tween({menuPosition: (someObject && someObject.position.x) || -MENU_WIDTH})
			.onComplete(() => this.closeTween.stop())
			.onUpdate(obj => (someObject.position.x = obj.menuPosition))
			.easing(TWEEN.Easing.Exponential.Out)
	}

	openMenu = () => {
		this.menuOpen = true

		if (this.closeTween && this.closeTween.isPlaying()) this.closeTween.stop()

		this.makeOpenTween()
		this.openTween.to({menuPosition: -MENU_WIDTH}, 800).start()
		this.tweenLoop()
	}

	closeMenu = () => {
		this.menuOpen = false

		if (this.openTween && this.openTween.isPlaying()) this.openTween.stop()

		this.makeCloseTween()
		this.closeTween.to({menuPosition: 0}, 800).start()
		this.tweenLoop()
	}

	toggleMenu = () => (this.menuOpen ? this.closeMenu() : this.openMenu())

	tweenLoop() {
		if (this.tweenRAF) return

		this.tweenRAF = requestAnimationFrame(function loop(t) {
			if (this.openTween && this.openTween.isPlaying()) this.openTween.update(t)
			else if (this.closeTween && this.closeTween.isPlaying()) this.closeTween.update(t)
			else return (this.tweenRAF = null)
			this.tweenRAF = requestAnimationFrame(loop)
		})
	}
}
```

</details>

<details><summary>after this change, 37 lines of code needed (cleaner, simpler logic, more efficient):</summary>

```js
class ExampleAfterAPIChanges {
	tween = new TWEEN.Tween({menuPosition: 0}, {group, rememberLastValues: true})
		.onComplete(() => this.openTween.stop())
		.onUpdate(obj => (someObject.position.x = obj.menuPosition))
		.easing(TWEEN.Easing.Exponential.Out)

	menuOpen = false
	tweenRAF = null

	openMenu = () => {
		this.menuOpen = true

		if (this.tween.isPlaying()) this.tween.stop()

		this.tween.to({menuPosition: -MENU_WIDTH}, 800).start()
		this.tweenLoop()
	}

	closeMenu = () => {
		this.menuOpen = false

		if (this.tween.isPlaying()) this.tween.stop()

		this.tween.to({menuPosition: -MENU_WIDTH}, 800).start()
		this.tweenLoop()
	}

	toggleMenu = () => (this.menuOpen ? this.closeMenu() : this.openMenu())

	tweenLoop() {
		if (this.tweenRAF) return

		this.tweenRAF = requestAnimationFrame(function loop(t) {
			this.tween.update(t)
			if (this.tween.isPlaying()) this.tweenRAF = requestAnimationFrame(loop)
			else this.tweenRAF = null
		})
	}
}
```

</details>

This is what the above code does (transitioning back and forth any time I click):

![example](https://user-images.githubusercontent.com/297678/83293991-684e7400-a1a1-11ea-9c49-8607bdeb2451.gif)

> **Note** The current behavior allows the exact animation to be repeated as described, which is better default behavior.

---

For stumblers, https://github.com/tweenjs/tween.js/issues/643 shows a workaround in case you need this right now.

**Comment by trusktr** [comment]
To make this work, it also depends on https://github.com/tweenjs/tween.js/issues/512 being fixed, moving the state modification inside of `Tween` instead of `Group`, otherwise in my `after` example the checks for `isPlaying()` will not work as expected.

**Comment by trusktr** [comment]
Tracking this in the new [General Project Board](https://github.com/tweenjs/tween.js/projects). Feel free to start adding issues into the board, and we can prioritize by dragging more important items to the top.

**Comment by trusktr** [comment]
Should `stop` reset things, instead of having a new `reset` method? I need to verify what currently happens with `stop`/`start`.

**Comment by dalisoft** [comment]
Yep, this makes development easier. Also this can be implemented without loss of much performance (which i did some years ago for my library).
Good idea

**Comment by trusktr** [comment]
In CSS, a feature similar to this is configurable and is called [`animation-fill-mode`](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-fill-mode).
