### ISSUE TITLE
Question: TWEEN.Group() example?

### ISSUE THREAD

**Issue by ManuVanneste** [tweenjs/tween.js#548]
I can’t actually find a complete example of working with TWEEN.Groups(), am trying to understand why the code below doesn't do the job. I even checked the tests.js file, … Can someone help me out?

Thx!
Manu 

var groupA = new TWEEN.Group()

var _var={x: 1}
var _tar={x: 100}

var tweenA = new TWEEN.Tween(_var).to(_tar, 2000).group(groupA);
tweenA.easing(TWEEN.Easing.Quadratic.InOut);
tweenA.onUpdate(function(){
    console.log('A',_var)
});

tweenA.start()
groupA.update()

**Comment by mikebolt** [comment]
No time passes between the call to tweenA.start() and groupA.update(). You need to call the update function in a requestAnimationFrame callback. Try to fix that then let me know if there are still any problems.

**Comment by trusktr** [comment]
f.e.

```js
function loop(time) {
  if (groupA.update(time)) requestAnimationFrame(loop)
}

loop()
```

`groupA.update(time)` needs to be called with the time to set the animation to. It returns false if the time has gone past the end of the animation duration, and in that case you will want to stop the loop.

**Comment by trusktr** [comment]
Based on your code example, we think that solves the issue. Let us know if it doesn't. :)

**Comment by ManuVanneste** [comment]
Thx guys.
