### ISSUE TITLE
tw.onComplete() is not called when tw.end()

### ISSUE THREAD

**Issue by famibee** [tweenjs/tween.js#551]
This is a bug that occurred in 18.6.0.
 It does not occur in 18.5.0.

 The execution environment is the latest.
【macOS Catalina 10.15.5】
・Google Chrome 83.0.4103.106（Official Build） （64 ビット）
・Safari バージョン13.1.1 (15609.2.9.1.2)
etc.

 Thanks.

**Comment by trusktr** [comment]
@famibee Hello, thanks for reporting this! Can you provide a small code example (f.e. on http://jsfiddle.net or http://codepen.io).

Let's get a test case added for this.

**Comment by famibee** [comment]
・tween.js(18.5.0) https://codepen.io/famibee/pen/zYqbZoB
・tween.js(18.6.0) https://codepen.io/famibee/pen/abNMpYb

When tween is stopped () & end () (click to execute in sample)
・ In 18.5.0, it was moved to stop & end.
-It stopped in 18.6.0, but did not move to the end. onComplete () is no longer called.
> tweenをstop()＆end()したとき（サンプルではクリックすると実行する）、
> ・18.5.0では停止＆終端へ移動していた。
> ・18.6.0では停止するが終端へ移動しなくなった。onComplete()が呼ばれなくなった。

In summary, in 18.6.0
-If you stop () and then end (), end () is no longer called.
It seems that you should call end () directly without stop (). (Right click to execute)
-Then, only onComplete () is called while it keeps moving.
In that case, I thought I should do tw.end (). Stop (), but for some reason it doesn't stop.
If tw.stop (); is called in onComplete (), the terminal will be stopped, so it is currently supported as such.
> まとめると、18.6.0では
> ・stop()してからend()するとend()が呼ばれなくなった。
> 　stop()せずend()を直接呼べばよいようだ。（右クリックで実行する）
> ・すると動き続けたままでonComplete()だけ呼ばれてしまう。
> 　それなら tw.end().stop() すればよいかと思ったが、なぜか停止しない。
> 　onComplete()内でtw.stop();を呼ぶと終端停止するので、現状そのように対応している。

`.onComplete(()=> {mes.textContent = 'onComplete 🍇'; tw.stop()})`

**Comment by trusktr** [comment]
Interesting, thanks for the examples! Here's the plan:

- for v18 we will restore the previous behavior (f.e. release it in `18.6.2`)
- For a breaking release (f.e. v19) we should decide which behavior we want. Maybe we want both `stop()` and `complete()` methods so people can choose the intent? Or something?

**Comment by trusktr** [comment]
fix: https://github.com/tweenjs/tween.js/pull/573

**Comment by trusktr** [comment]
Released in `v18.6.2`. Demo: https://codepen.io/trusktr/pen/60702e496997f2584956d6d0922116fd
