### ISSUE TITLE
in 18.6.0 I get a typescript error when calling tween.start()

### ISSUE THREAD

**Issue by leon** [tweenjs/tween.js#552]
I think it's because of the non optional time parameter to start.

`tween.start(time: number)` it should be `tween.start(time?: number)`

Or is there anything else I'm missing?

**Comment by mikecann** [comment]
Ye exactly same issue

**Comment by trusktr** [comment]
Ah, yep! Thanks for reporting! Indeed it should be changed. I will fix this
soon unless someone makes this simple PR before I get to it. :)

#!/JoePea

**Comment by jedahan** [comment]
is there a workaround for this we can use in the meantime?

**Comment by jedahan** [comment]
(also same issue with `.update`)

**Comment by IvoCastillo** [comment]
Has there been any progress on this ?

**Comment by IvoCastillo** [comment]
https://github.com/tweenjs/tween.js/pull/558
seems to be ready for merging any day now

**Comment by IvoCastillo** [comment]
It worked for me if you make the parameter in start of "undefined". Maybe it will work for you as well

**Comment by trusktr** [comment]
Merged https://github.com/tweenjs/tween.js/pull/558. Thanks!

**Comment by trusktr** [comment]
Released in `18.6.1`
