### ISSUE TITLE
strange typescript integration and type defintion

### ISSUE THREAD

**Issue by steve3d** [tweenjs/tween.js#553]
first of all, thank you all for creating this amazing library, and now it finally support typescript. I'm a user of angular, so that means I use typescript a lot, but this package is very strange, as follows:

- most typescript libraries I use have these parts in their `package.json`
```
  "es2015": "fesm2015/ng-select-ng-select.js",
  "esm2015": "esm2015/ng-select-ng-select.js",
  "esm5": "esm5/ng-select-ng-select.js",
  "fesm2015": "fesm2015/ng-select-ng-select.js",
  "fesm5": "fesm5/ng-select-ng-select.js",
```
but tween.js don't have any of this part.

- a lot of angular libraries have this `  "typings": "ng-select-ng-select.d.ts",` in their `package.json`, but tween.js only has `"types": "dist/index.d.ts",` in `package.json`

- most typescript library can be imported by use `import { animationFrameScheduler, interval, Observable } from 'rxjs';`, but if I use `import TWEEN from '@tweenjs/tween.js';` then I have to add `allowSyntheticDefaultImports` option into tsconfig.json, otherwise it simply won't compile. without the `allowSyntheticDefaultImports` option, I have to use `import * as TWEEN`, 

all these feels very strange to me as a typescript user.

**Comment by steve3d** [comment]
sorry, no errors after I did a clean and reinstall.

**Comment by trusktr** [comment]
@steve3d The type definitions and exports have been improved in `18.6.1`, in case you still had any issues.
