### ISSUE TITLE
Clock synchronization issue

### ISSUE THREAD

**Issue by christopherjbaker** [tweenjs/tween.js#560]
When controlling the clock by passing a value to `TWEEN.update(...)`, the default `_startTime` for a tween started with `.start()` still uses the browser clock, which means tweens do not behave as expected. I've fixed this in my own code by redefining `TWEEN.now` to return the last value I sent to `.update(...)`. It seems to me that if its in a "controlled mode", everything should use those controlled values.

**Comment by trusktr** [comment]
That change may work for your case, but I think it may break individually-controlled Tweens. `TWEEN.now()` is merely supposed to be an API in place of `performance.now()` in case some browser doesn't have that.

If interested to make a PR but adding this feature behind an API more like `TWEEN.lastTime()` or similar, and update the tests, that would be great!

**Comment by trusktr** [comment]
Do you have a code snippet that demonstrates what issue you had?

**Comment by christopherjbaker** [comment]
I don't have a code snippet, but here is how you can recreate it:
1. Set up a RAF that calls `TWEEN.update(Date.now() + 2500)`. This sets up the internal clock so that it will _not_ line up with the browser's clock. In my case, I'm using threejs's clock, which tracks in seconds instead of ms.
2. Set up an animation that will take 5 seconds to complete. Do not pass any arguments to `start()`.
3. Observe that it does not behave as intended. I believe in this case, it will start halfway done, because it "started" at the current time, but the update was called with the current time + 2.5 seconds.

You've provided control of the internal clock, but you don't use the custom clock values when you start a tween, so they start in a different timeframe than the updates.

**Comment by trusktr** [comment]
Interesting, haven't used it like that before. Normally what I do is control every tween individually, which may be a workaround for now:

```js
const tween = new Tween(...)....start(startTime)
// ...
tween.update(newTime)
```

That way each tween can operate with its own custom time being passed in (plus easier to encapsulate the tween to a particular component of your UI, pause it individually, update it individually, etc, while other tweens in other components can also do their own thing).

**Comment by audiodude** [comment]
I'm going to try and write a PR that addresses this, because I've been bitten by it too when trying to programmatically step through time while using tween.js.

**Comment by audiodude** [comment]
Here's the basic idea of what I'm trying to do: https://jsfiddle.net/audiodude/anL0tzux/32/

**Comment by audiodude** [comment]
Sorry for all the comments. I figured out that the problem with my actual code is that I call start later after creating the tween, which I'm having trouble producing a minimal example of. I guess the workaround is to call start with an explicit startTime.

**Comment by mikebolt** [comment]
Here's an idea. We could add a property to Group that would tell tween.js to expect that the group will have its time value manually controlled.

**Comment by trusktr** [comment]
Yeah, I thought the same. Basically if you use a `Group`, the the Group can call APIs and it will be sure to pass in the time to each tween instead of letting the tweens determine it.

Also it seems as if Tween is trying to do everything, but maybe in a breaking change we can split concepts into `Timeline`, `Keyframe` (Timeline has Keyframes, and perhaps remove the `.chain` API because then you just make a Timeline), `Tween` (does only tweening and does it well, and not much else), etc, you can imagine where I'm going with this idea. Food for thought...

**Comment by trusktr** [comment]
Will close after thinking again about this because the expectation is that if we want to manage time ourselves, we can pass in the values to both `start(time)` and `update(time)`, knowing exactly what we want. F.e.

```js
tween.start(performance.now() + 2500)

requestAnimationFrame(function loop(now) {
  tween.update(now + 2500)
})
```
