### ISSUE TITLE
TypeScript : Type of first parameter for "update" & "start" method should be "number?", not "number"

### ISSUE THREAD

**Issue by WolfgangKurz** [tweenjs/tween.js#565]
All examples using `TWEEN.update()` and `TWEEN.Tween(~) ... .start()` without any parameters.

But Type Definition and SourceCode defined parameter like below,
``` typescript
	update(time: number, preserve?: boolean): boolean {
```

`time` parameter should be `time: number?`

**Comment by trusktr** [comment]
Hello! This is fixed in https://github.com/tweenjs/tween.js/pull/558. We should release soon.

**Comment by WolfgangKurz** [comment]
OK, Thanks.

**Comment by trusktr** [comment]
Released in `18.6.1`
