### ISSUE TITLE
Wrong latest version on npm

### ISSUE THREAD

**Issue by vkrol** [tweenjs/tween.js#584]
Hi.

17.6.0 was marked as `latest` on npm. It seems to be a mistake.

![image](https://user-images.githubusercontent.com/153412/97087247-63e39580-1631-11eb-9b14-b8583a32080a.png)

**Comment by trusktr** [comment]
Oops. That is meant to be a fix for v17. Not sure how to publish a release for an older branch and have it not be `latest`. Let me see...

**Comment by trusktr** [comment]
Ok, I think I fixed this. Thanks for pointing it out by the way! Still shows the old tag on npmjs.com, but maybe it takes some time.
