### ISSUE TITLE
TypeScript declaration file forces to pass timestamp to start() method

### ISSUE THREAD

**Issue by HusakYurii** [tweenjs/tween.js#588]
Hi folks! 
I used `tween.js` in context of JS and never had issues with starting a new tween, but in context of TS `index.d.ts` file forces you to pass a timestamp to `Tween.prototype.start` (wich is optional).
In case when I pass 0 the tween may not be animated becaues update loop considers it as finished . By passing `performance.now() `this issue is not happening.

Dependencies I used
```json
    "dependencies": {
        "@tweenjs/tween.js": "^18.6.0",
    },
   "devDependencies": { 
       "@types/tween.js": "^18.5.1",
    }
```
Code example describing the issue
```javascript
             new TWEEN.Tween({ })
                .to({ }, 330)
                .start(window.performance.now()); // tween will run with NO  issues

             new TWEEN.Tween({ })
                .to({ }, 330)
                .start(); // ts complains because in index.d.ts file start(time: number): this;

             new TWEEN.Tween({ })
                .to({ }, 330)
                .start(0); // ts DOES NOT complain, but tween is considered as finished on timeline
```
Can it be that index.d.ts file is not updated or maybe there is a right way to install @types and reference them in tsconfig.json file?

**Comment by trusktr** [comment]
Hello! This is already fixed.

As of `18.6.0`, the `@types/tween.js` package is no longer needed. You should delete that dependency.

Try version `^18.6.4` in your package.json. If that still doesn't work, try deleting `node_modules` then reinstall (to be sure the `@types` package is gone and the new tween.js is in).

**Comment by trusktr** [comment]
Here's a codesandbox with latest Tween.js. Try hovering on `tween.start()` to see the new type signature: https://codesandbox.io/s/ecstatic-firefly-mmptp?file=/src/index.js

**Comment by trusktr** [comment]
I'll close, but feel free to open if you have any other issue. :)

**Comment by HusakYurii** [comment]
@trusktr thank you for the tips!
