### ISSUE TITLE
How to stop tween chain？

### ISSUE THREAD

**Issue by xujunpro2** [tweenjs/tween.js#592]
tween.chain(tween1);            
tween1.chain(tween2);
tween.start();
setTimeout(function(){
     tween.stop();
    console.info('stop')},
3000);
After 3 seconds, the first tween has been executed. At this point, calling tween.stop(); animation will continue to execute. How do i stop tween chain？

**Comment by mikebolt** [comment]
The chain function has been problematic for a long time. I'm in favor of making a breaking change to the chain function so that it is more intuitive. So now the question is "How should the chain function work?" I would like to read some suggestions.

**Comment by trusktr** [comment]
@xujunpro2 Hello! What version are you on? Can you make a live example of the problem on codepen?

Here's is a basic codepen example you can start from:

https://codepen.io/trusktr/pen/OJRQjZw

From the latest examples in the repo, and I see chained tweens are able to stop in the `11_stop_all_chained_tweens`:

![stop-chained-tweens](https://user-images.githubusercontent.com/297678/103389045-647d2a00-4ac1-11eb-95e1-211c97767831.gif)

You can run the latest example by cloning the repo, then

```bash
npm install
npm run build
npm run examples
```

and opening your browser to http://localhost:5000/examples, and in particular see http://localhost:5000/examples/11_stop_all_chained_tweens

---

Sidenote @mikebolt I have upcoming changes in the `gh-pages` (to keep the website up to date automatically) and `fix-dynamic-to-with-array-values branches`.

**Comment by trusktr** [comment]
> The chain function has been problematic for a long time. 

I believe the issues have been fixed, in particular stopping chained tweens as with the example, and new tests.

**Comment by trusktr** [comment]
Closing as per above.
