### ISSUE TITLE
Critical dependency issues

### ISSUE THREAD

**Issue by morecoffee101** [tweenjs/tween.js#599]
Our sonar scanner identified the following critical dependency issues in tween.js

| Package name | Version | Security issue | Resolved by using version |
|---|---|---|---|
dot-prop | 4.2.0 | sonatype-2020-0018 | 4.2.1 or >= 5.1.1
execa | 0.7.0 | sonatype-2019-0206 | 2.0.1
fstream | 1.0.11 |  sonatype-2019-0224  | 1.0.12 
ini | 1.3.5 | sonatype-2020-1214 | 1.3.6
npm-user-validate | 1.0.0 | sonatype-2020-1018 | 1.0.1
opener | 1.5.0 | sonatype-2020-0887 | 1.5.2

Most of the dependencies are minor changes with the exception of execa.

**Comment by trusktr** [comment]
Thanks! These are all dev dependencies so it's no biggie.
