### ISSUE TITLE
it would be nice to be able to get the duration we assign to a tween

### ISSUE THREAD

**Issue by cesarl94** [tweenjs/tween.js#600]

**Comment by trusktr** [comment]
It's stored on this property:

https://github.com/tweenjs/tween.js/blob/ae24c58c8b57b2079151ae2c3c63f2bb501c8b2b/src/Tween.ts#L26

But it is marked as private if you're using TypeScript. No problem in plain JS though. It likely won't change.

I think we can do something special like `duration()` without an argument returning the current value, or something.

**Comment by trusktr** [comment]
available in v23.1.0
