### ISSUE TITLE
Keep website and README in sync

### ISSUE THREAD

**Issue by trusktr** [tweenjs/tween.js#603]
We should make a GitHub action so that when we update our README it automatically goes to the website. At the moment, our [README](https://github.com/tweenjs/tween.js/blob/master/README.md) is out of sync with the [website](https://tweenjs.github.io/tween.js). The repo's README should be the source for the website.

**Comment by kangthink** [comment]
Hi, I think the website link is wrong which directs to `https://github.com/tweenjs/tween.js/issues/tweenjs.github.io/tween.js`.

**Comment by trusktr** [comment]
This has been handled, the website is published from our `main` branch (we don't use `master` anymore). So, simply merge any PR to `main` and the website gets updated. Yay.
