### ISSUE TITLE
Properties of Easing object can reassignment

### ISSUE THREAD

**Issue by MasatoMakino** [tweenjs/tween.js#610]
## Description

All properties of the `TWEEN.Easing` object allow reassignment.

## Expected Behavior

Easing functions and groups in `TWEEN.Easing` do not allow reassignment.

## Actual Behavior

Easing functions and groups in `TWEEN.Easing` allow reassignment.

## Steps to Reproduce

Open [code pen](https://codepen.io/masatomakino/pen/NWdQjqx)

This is a problem section.

```js
TWEEN.Easing.Quadratic = TWEEN.Easing.Linear;
TWEEN.Easing.Cubic.In = TWEEN.Easing.Bounce.Out;
```

This code can be run without causing any errors.

## Impact

In any scope, `Easing` can be reassignment. If someone accidentally reassignment easing functions, it will be difficult to identify the problem.

## Proposal

Ideally, if we try to reassign to TWEEN.Easing, we will get an error.
Even if no error is thrown, this issue will be resolved if the reassignment is ignored.

- Remove `Easing` global object
- Remove default export in Easing.ts
- Change each EasingFunctionGroup (e.g. Quadratic, Cubic) to Class.
- Change each EasingFunction to static functions
- Change Easing import in index.ts to `import * as Easing from ". /Easing.ts"`

With this change, I think it will possible to ignore reassignments without losing compatibility.

## Environment

macOS 10.15.7
Google Chrome 90.0.4430.93
tween.js 18.6.4

**Comment by trusktr** [comment]
What if we apply Object.freeze?

**Comment by MasatoMakino** [comment]
I compared the two approaches. `Object.freeze` and `static functions`

## Points in common between the two approaches

### Both of these approaches use Object.freeze. 

If we remove a default export of Easing.ts, this code transpiled by tsc will look like this. You can see that `Easing` is frozen.

```js
var Linear = /** @class */ (function () {
    function Linear() {
    }
    Linear.None = function (amount) {
        return amount;
    };
    return Linear;
}());
// export default Easing

var Easing = /*#__PURE__*/Object.freeze({
    __proto__: null,
    Linear: Linear
});
```

Therefore, when we try to change a property, the behavior is the same.

### Compatibility can be confirmed by testing

Tests added in #608 will confirm that Easing keeps a compatibility after modify.

## Object.freeze

### Advantage

- No change to existing code

### Disadvantage

- Object.freeze can't freeze nested objects. Therefore, we need to implement [deepFreeze](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze)

## static

### Advantage

- Maintenance is easier because each EasingFunctionGroup is a separate class. It's classes can be split into files.
- Type definitions for Easing will be clear. [Related comments](https://github.com/tweenjs/tween.js/pull/608#discussion_r624424084)

### Disadvantage

- Need to modify the existing code, Compatibility is confirmed by testing.

**Comment by MasatoMakino** [comment]
> What if we apply Object.freeze?

With this in view, I did some research on how to implement it.

- Object.freeze makes properties, including functions, unchangeable.
- Object.freeze does not support nested objects. [Reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze)
- Static functions are reassignable. class and static functions do not solve this issue.

There was also a review of whether to include the type definition of EasingFunctionGroup in Easing.ts.
https://github.com/tweenjs/tween.js/pull/608#discussion_r624423020
I could not find a way to expose EasingFunctionGroup interface to outside while exporting Easing global object as default. If you have that information, please let me know.

## Proposal

Based on these results, I modify the proposal.

- Remove Easing global object
- Remove default export in Easing.ts
- Change each EasingFunctionGroup (e.g. Quadratic, Cubic) to _frozen object._
- Change Easing import in index.ts to import * as Easing from ". /Easing.ts"

This is a sample of Easing.ts

```js
export type EasingFunction = (amount: number) => number

export interface EasingFunctionGroup {
	In: EasingFunction
	Out: EasingFunction
	InOut: EasingFunction
}

export const Linear = Object.freeze({
	None: (amount: number): number => {
		return amount
	},
})

export const Quadratic = Object.freeze(<EasingFunctionGroup>{
	In: (amount: number): number => {
		return amount * amount
	},
	Out: (amount: number): number => {
		return amount * (2 - amount)
	},
	InOut: (amount: number): number => {
		if ((amount *= 2) < 1) {
			return 0.5 * amount * amount
		}

		return -0.5 * (--amount * (amount - 2) - 1)
	},
})
```

### Test

I tested this sample in these environments

- TypeScript + tween.esm.js + tween.d.ts : tsc error
- Chrome + tween.umd.js : Uncaught TypeError: Cannot assign to read only property 'Quadratic' of object
- node.js + tween.cjs.js : No error, but ignored.
- nodeunit + tween.cjs.js + rollup.js + @ts-ignore : I can reassign EasingFunctionGroup, but I cannot be reassigned Easing function

If I did not ignore tsc errors intentionally, I got the best results.

If you find any problems with this proposal, please let me know.
Thanks.

**Comment by trusktr** [comment]
@MasatoMakino Hello again. sorry for taking so long. Let's apply `Object.freeze()` to the objects, but without changing the export format (because that is a breaking change). f.e.

```js
const Easing = Object.freeze({
	Linear: Object.freeze({
		None: function (amount: number): number {
			return amount
		},
	},
	// ... etc ...
})

export default Easing; // same export, no breaking change
```

**Comment by trusktr** [comment]
Another idea is using `as const` for type checking only, for example:

<img width="303" alt="Screenshot 2023-04-02 at 2 41 02 PM" src="https://user-images.githubusercontent.com/297678/229380597-91d423d9-cd07-4fa8-a56a-492c4350f72b.png">

[TS playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZiEMC8MDeBYAUDXCQBcMAjAEwDMM2AvjAIYQyiRRA)

**Comment by trusktr** [comment]
By the way also @MasatoMakino, are you interested to join the org and help maintain and expand Tween.js?
