### ISSUE TITLE
Circular dependency issue

### ISSUE THREAD

**Issue by alikharrat** [tweenjs/tween.js#618]
Hi,
i'm having a little problem with the library after running npm run build:

.tmp/Index.js → dist/tween.umd.js, dist/tween.amd.js, dist/tween.cjs.js, dist/tween.esm.js...
created dist/tween.umd.js, dist/tween.amd.js, dist/tween.cjs.js, dist/tween.esm.js in 119ms

.tmp/tests.js → .tmp/tests.cjs.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@sinonjs/fake-timers (imported by .tmp\tests.js)
created .tmp/tests.cjs.js in 210ms

./.tmp/Index.d.ts → dist/tween.d.ts...
(!) Circular dependency
.tmp\Group.d.ts -> .tmp\Tween.d.ts -> .tmp\Group.d.ts
created dist/tween.d.ts in 64ms

is that normal?

**Comment by trusktr** [comment]
Hello! This isn't clear. It would be better to post exact commands you ran, and exact output, and a reproduction if you can.

**Comment by alikharrat** [comment]
> Hello! This isn't clear. It would be better to post exact commands you ran, and exact output, and a reproduction if you can.

I executed the exact same commands on the Installation

git clone https://github.com/tweenjs/tween.js
cd tween.js
npm i .
npm run build

nothing less nothing more. (sorry for the delay i was away for some days)

**Comment by trusktr** [comment]
Yes, this is fine, these are harmless messages.
