### ISSUE TITLE
tweening to arrays of values has bug

### ISSUE THREAD

**Issue by tvytlx** [tweenjs/tween.js#620]
`_valuesEnd[property]`'s length will grow endless, because it's a reference to `this.valuesEnd`

https://github.com/tweenjs/tween.js/blob/8db070d25a82c19772352bbcbc33a326e6882b4e/src/Tween.ts#L138-L150

checking this demo, just click the start button twice or more: https://jsbin.com/hulidowipa/edit?html,js,output

**Comment by tvytlx** [comment]
@trusktr hi, could you please check my pr? 🙏

**Comment by trusktr** [comment]
Hello, sorry for the late reply. Thanks for looking at this!

The build in the PR has an error with Prettier? Would you mind adding a small unit test for this?

**Comment by trusktr** [comment]
fixed in #621
