### ISSUE TITLE
我写了一套android的属性动画，动画核心使用了tween的风格，求授权。

### ISSUE THREAD

**Issue by wufuqi123** [tweenjs/tween.js#629]
我的属性动画核心使用了跟tween一样的风格。
Easing.java 的代码使用了 Easing.js 的计算。

https://github.com/wufuqi123/WuKongAnimation

求授权

**Comment by trusktr** [comment]
Hey, no problem. A link in a comment would be nice but not required. F.e. `// adapted from https://github.com/tweenjs/tween.js/blob/9f8c56c4d5856a970b45895bb58cd9d1d56cf3ea/src/Easing.ts`

**Comment by wufuqi123** [comment]
谢谢，我在Easing（缓动函数）添加了跳转链接

**Comment by trusktr** [comment]
Thanks! Happy coding! :)
