### ISSUE TITLE
this._easingFunction is not a function. How to resolve it?

### ISSUE THREAD

**Issue by zanetti4** [tweenjs/tween.js#634]
I'm using tween.js like this. 
```javascript
var tween = new TWEEN.Tween(coords)
			.to(toCoords, 1000)
			.easing(TWEEN.Easing.Linear.Out)
			.onUpdate(function(){
				// Called after tween.js updates 'coords'.
				mesh.position.set(coords.x, coords.y, coords.z);
			})
			.start();
```
I get the error 'Uncaught TypeError: this._easingFunction is not a function.' when it runs. How to resolve it? It runs well if I delete the easing method. Thanks a lot!

**Comment by trusktr** [comment]
That's peculiar. The code seems fine. If you can provide a reproduction that would help to see what's happening.

**Comment by trusktr** [comment]
Oh! Of course. There is no `In` or `Out` for `Linear` easing, just use `TWEEN.Easing.Linear`.

**Comment by zanetti4** [comment]
Yes, it is. I use `TWEEN.Easing.Linear.None` and then the programme is fine. Thank you very much!
