### ISSUE TITLE
Help wanted :)

### ISSUE THREAD

**Issue by mikebolt** [tweenjs/tween.js#638]
Hi everyone. I haven't worked on this project in a long time due to work and other interests. I don't think I'm going to work on this much in the future, and because there hasn't been much development in the last few years it looks like we need some maintainers.

So, to current and previous maintainers, do you need me to change anything on GitHub or npm?

And, to anyone else reading this, if you have ever looked through the source code, or if you want to, then more help is definitely welcome.

I'm posting this here because https://github.com/tweenjs/discuss hasn't been used in a long time, but this conversation could be continued over there.

**Comment by trusktr** [comment]
Hi @mikebolt. I'm still here and have some ideas, but haven't circled back yet.

- A `Timeline` feature: the idea is to decouple a Tween from the concept of an organized series of tweens, right now `tween.chain()` is trying to bite more than it can chew (f.e. it does not easily allow parallel animations, overlapping animations, etc).
- Compiling Tween.js to WebAssembly with a toolkit I've been collaborating on to compile TypeScript to WebAssembly and native.

If someone else is interested in collaborating, I can help ramping up and discussing. Please do reach out!

> https://github.com/tweenjs/discuss hasn't been used in a long time

I went ahead and archived that after putting a link to https://github.com/tweenjs/tween.js/discussions there.

**Comment by mk965** [comment]
@trusktr 

I really want to join. Please feel free to contact me if I can be of help.

**Comment by cuixiping** [comment]
I like this lib and may contribute some code some time. I am using tweenjs for my games.

**Comment by trusktr** [comment]
@cuixiping @mk965 would be glad to have some help. If any ideas, please let me know. The issues list has some existing things to do. We need to fix

- https://github.com/tweenjs/tween.js/issues/666

with higher priority.

**Comment by cuixiping** [comment]
@trusktr 
As my test, similar to #666 , 
* rename `tween.esm.js` to `tween.mjs`
* rename `tween.cjs.js` to `tween.cjs`
* modify `package.json`
  * set "main" as mjs file "dist/tween.mjs"
  * remove "module" field

```
{
	"type": "module",
	"main": "dist/tween.mjs",
	"types": "dist/tween.d.ts",
	"exports": {
		".": {
			"import": "./dist/tween.mjs",
			"require": "./dist/tween.cjs"
		}
	},
}
```

My testing steps:

* create a new folder and run `npm init` and then `npm install @tweenjs/tween.js`
* create a `index.mjs` in this folder with content
```
import * as TWEEN from '@tweenjs/tween.js'
console.log(Object.keys(TWEEN));
```
* create a `index.cjs` in this folder with content
```
const TWEEN = require('@tweenjs/tween.js')
console.log(Object.keys(TWEEN));
```
* run `node ./index.mjs` works ok!
* run `node ./index.cjs` works ok!

My node.js version is `16.16.0`

**Comment by trusktr** [comment]
Hey thanks @cuixiping! Can you test with the latest? `.cjs.js` was renamed to `.cjs`, but everything else should just work. 

The new examples in `examples/example-projects/nodejs-commonjs/` and `examples/example-projects/nodejs-esmodules/` verify being able to import into Node.js with either CommonJS or ESM format, with code similar to what you wrote with `console.log`.

We did not need to rename the `.esm.js` to `.mjs` because `.js` is already treated as ESM with `type: module` in package.json. Maybe just `tween.js` would be a nicer name, but decided not to make a breaking change for that.

**Comment by trusktr** [comment]
@cuixiping @mk965 added you both to the repo! Will close this for now.

If anyone else is interested to volunteer some time on this, aiming to move towards a feature like [`Timeline`](https://github.com/tweenjs/tween.js/issues/647) for managing timelines with tweens after [simplifying some things](https://github.com/tweenjs/tween.js/issues/655), please reach out!

**Comment by dalisoft** [comment]
@trusktr Please see #710 and https://github.com/tweenjs/es6-tween/issues/117

**Comment by trusktr** [comment]
The project is active at the moment, `Timeline` is almost done. Unpinning.

After Timeline we can make a UI for it.
