### ISSUE TITLE
Has .dynamic() been deprecated in the v19 version?

### ISSUE THREAD

**Issue by mk965** [tweenjs/tween.js#642]
Has `.dynamic()` been deprecated in the v19 version?

When I use the v19 version I found that `dynamic` throws an error: 

<img width="842" alt="image" src="https://user-images.githubusercontent.com/30465793/230355343-38a5a0a8-f9b3-4e73-b2eb-7531034de06d.png">

DEMO: [https://codepen.io/mk965/pen/RwewVQJ](https://codepen.io/mk965/pen/RwewVQJ)

**Comment by trusktr** [comment]
Hey, yeah, apparently we removed that when we did refactors to improve Tween overall. We have a plan in #555 and #585 to restore it. The PR is a mess though, it got lost in translation after converting from `master` to `main` and it is now conflicted.

I will close this in favor of #555. Please feel free to join in over there. :)

**Comment by trusktr** [comment]
Oh! Also you can use v17, dynamic to should work there for now.

**Comment by trusktr** [comment]
Oh, one more thing! The docs are out of sync. Sorry about that. Fixing that now.

You can look in the repo at the dynamic_to example, it works with objects. You don't need to call `dynamic()`, it just works out of the box. It currently doesn't work with arrays.

**Comment by trusktr** [comment]
The new `tween.dynamic(true)` feature has been released in v20, and docs are up to date, along with release notes.

https://github.com/tweenjs/tween.js/releases/tag/v20.0.0

**Comment by mk965** [comment]
> 新`tween.dynamic(true)`功能已在 v20 中发布，文档和发行说明都是最新的。
> 
> https://github.com/tweenjs/tween.js/releases/tag/v20.0.0

Yes, I found that the Chinese documentation is also seriously lagging, and I have now re-translated `user_guide` and `contributor_guide` (https://github.com/tweenjs/tween.js/pull/646).

I can also help translate other documents.

Maybe we can also create an official website.

**Comment by trusktr** [comment]
> create an official website

Got tweenjs.org, perhaps we can link it to GitHub Pages for now. We could move to [Docsify](https://docsifyjs.org) next (I'm a maintainer). Wdyt?

Here's another project of mine using Docsify: https://lume.io.
