### ISSUE TITLE
CJS entry point can't be loaded in Node.js

### ISSUE THREAD

**Issue by inukshuk** [tweenjs/tween.js#649]
I might be doing something wrong, but I believe there is an issue with the current dual package setup. Type is set to `module` but the CJS entry point `main` points to "dist/tween.cjs.js". Despite the `.cjs` in there the Node.js loader still sees the final `.js` extension. Based on the nearest `package.json` it will therefore default to using the ESM loader for this file.

As a result, you can't currently `require('@tweenjs/tween.js')` in Node. Unless I'm missing something [the `.js` extension should be dropped](https://github.com/tweenjs/tween.js/blob/main/rollup.config.js#L22).

**Comment by trusktr** [comment]
Thanks @inukshuk and @christjt for pointing these issues out!

**Comment by inukshuk** [comment]
Unfortunately the linked PR above doesn't address this issue. The CJS entry point needs to have a `.cjs` extension or the Node.js module loader will refuse to open it. The current `.cjs.js` one doesn't work.

**Comment by inukshuk** [comment]
I submitted a PR for this above. It just renames the CJS entry point (which breaks the naming scheme but I don't think there's a way around making the Node.js loader accept a CJS in an ESM package).
