### ISSUE TITLE
Is yoyo working as expected ?

### ISSUE THREAD

**Issue by vis-prime** [tweenjs/tween.js#687]
https://tweenjs.github.io/tween.js/examples/10_yoyo.html

Checked the yoyo example and all 4 circles seem to be going down correctly then teleporting to the start position ,then teleporting back down and then returning up

https://github.com/user-attachments/assets/f25722a5-971f-4049-8ea3-40cfc1a8613a

**Comment by trusktr** [comment]
Ah, sorry about that! v23.1.2 broke it, [the change](https://github.com/tweenjs/tween.js/pull/683) has been reverted, and a new v23.1.3 has been released. Looks like we didn't test that one well enough.

**Comment by trusktr** [comment]
Thanks for reporting this!
