### ISSUE TITLE
Breaking the chain of tweens 

### ISSUE THREAD

**Issue by justin-hackin** [tweenjs/tween.js#97]
When I stop a circular chain of tweens i.e. forward/backward, I would like my object to resume its original position back.  This means, if it's coming forward, it finished the forward and goes backward and stops or if it's going backwards it finishes its backward tween and stops.  Something like backwardsTween.breakChain().  Can I do this with tween.js ?  Does it sound like a useful feature ?

**Comment by Baccanno** [comment]
There is a stopChainedTweens() feature already that stops chained tweens as well, isn't it what you're looking for ?

**Comment by justin-hackin** [comment]
The project I was working on is long dead so I don't remember, content to have this closed, but thanks for addressing and sorry no reply
